### ISSUE TITLE
Bootstrap Icons - how to set

### ISSUE THREAD

**Issue by slitzer** [manyfold3d/manyfold#1358]
Heya,

Thanks for the great app, 

Just looking for some guidance to set the icons rather then the title name as the top bar is super messy now the collections etc have been moved up 

TIA

**Comment by Floppy** [comment]
You can set the icon in the settings page, down the bottom, in the library settings; there's an edit button. This definitely needs to move to a much more obvious place. But, while that will change the icon for a library, it won't save you any space, as the text still appears. You could reduce that text down though, that might help. 

Would an icon-only option be useful, or should it just happen automatically if there isn't enough space? Sorting out proper scaling and responsiveness of the top bar etc is quite high on my list, so there should be some fixes coming soon...

<img width="551" alt="Screenshot 2023-07-19 at 23 03 33" src="https://github.com/Floppy/van_dam/assets/3565/30788c05-b2bf-43c2-b90d-e149c14546c4">

**Comment by slitzer** [comment]
Heya,

thanks for your quick reply

I have found that, just not sure how so set them?

I used the URL but not sure how to actually set an icon , do i need to download and put the path in the field?

**Comment by Floppy** [comment]
ah, sorry, I get you. Yeah it's a bit obscure. The link below the field should take you to https://icons.getbootstrap.com/, and then you're looking for the name below the one you want - for instance, in this case, `arrows-fullscreen`. Put that in the box, and it should give you the custom icon in the top bar.

<img width="175" alt="Screenshot 2023-07-19 at 23 38 48" src="https://github.com/Floppy/van_dam/assets/3565/696a1898-19d3-4bb1-8b94-84b8894f87f0">

**Comment by slitzer** [comment]
That has helped at least align them now :)
![image](https://github.com/Floppy/van_dam/assets/12588795/6a6dbfbc-fe4e-48a1-891e-8f9ec8331da4)
Thank you and look forward to the updates

**Comment by Floppy** [comment]
Thanks for the screenshot! It's always useful to know how people are using the thing, that's many more libraries than I've ever had. Do you find yourself using those icons a lot? Would a dropdown "Libraries" menu be too annoying?

**Comment by Floppy** [comment]
There's much better help now for these, and I've filed the ideal "select from dropdown" solution in #2405, so I'm closing this one.
