### ISSUE TITLE
Option to raise problems for missing preview images or missing 3d models

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1414]
Ideally all models should contain a preview image, and certainly should contain a 3d model. It would be good to have a setting to raise problems if either of those are not true.

**Comment by slitzer** [comment]
would it be possible to have an ackknowledge / ignore option
I can get rid of the warning triangle as I have too many blue errors (inefficient STL) or similar, and would like to have the option to ignore it

**Comment by Floppy** [comment]
I was definitely thinking of adding an ignores option for a problem at some point - I should add that as a separate ticket. I think when I do this one, it'll be done as a customisable level of severity for all problems, including "off", so that should mean you can disable the warning completely. I similarly have a scary number of inefficient files, so I feel your pain!

**Comment by Floppy** [comment]
@slitzer I've filed that as a separate ticket, https://github.com/Floppy/van_dam/issues/1449
