### ISSUE TITLE
Add option to hide Problems

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1449]
Sometimes, it's OK.

**Comment by ToasterUwU** [comment]
+1 for this one, since i dont care that 4 of my STLs are have 'Problems' because they are in a "Inefficient file format: ASCII STL"

**Comment by Floppy** [comment]
I think I have about 30 pages of those, so... yeah 😄

**Comment by Floppy** [comment]
@slitzer you may be interested to know that this is in the next release, coming soon :)
