### ISSUE TITLE
Browser right click menu

### ISSUE THREAD

**Issue by lloydpick** [manyfold3d/manyfold#1578]
The canvas html tag with id `webgl` is screen wide and is hijacking the right click menu. As there's now a blank image across the whole page. Can't right click and select the standard options as I only get this one instead...

<img width="194" alt="Screen Shot 2023-10-18 at 11 20 09 AM" src="https://github.com/Floppy/van_dam/assets/71318/8243ddaf-bb14-41e8-a2cb-e9766cddfa46">

**Comment by Floppy** [comment]
Ooh, good spot, thanks! I should definitely fix that, I hate that kind of thing. Probably need to push it behind all the other content with a z-index or something.
