### ISSUE TITLE
Moderation & User Administration tools

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1694]
## References 

* https://blog.joinmastodon.org/2018/07/cage-the-mastodon/

## Features

* [x] https://github.com/manyfold3d/manyfold/pull/2969
* [x] #2992
* [x] #3209
  * [x] #3215 
  * [x] #3216
  * [x] #3219 
  * [x] #3217 
* [x] #3220
* [x] #3259
* [x] #3250
* [x] #3257
* [x] #3221

**Comment by feroxib** [comment]
I guess with the "control over federation" LDAP, SAML and the likes are included?

**Comment by Floppy** [comment]
I think that will come later, along with more options for user SSO

**Comment by poVoq** [comment]
Linking to external OIDC / Oauth2 sources would be nice.

My usecase would be a supplementary service to a Forgejo git forge and that would allow integrating user accounts very easily.

I think this should be fairly easy to add with standard Rails social auth features (those log in with Google etc. buttons).

Thanks!

**Comment by Floppy** [comment]
Funny you should mention that... OIDC support went into main yesterday, and is awaiting release hopefully tomorrow! If you'd like to test it, pull the `edge` image and look at #2946 for how to enable it.

**Comment by poVoq** [comment]
Oh, very nice. I guess I need to look into setting up an instance then. Thanks!
