### ISSUE TITLE
UX Feedback

### ISSUE THREAD

**Issue by Rukongai** [manyfold3d/manyfold#1701]
First, let me preface that I understand this project is young, still under development, and a massive undertaking. I just wanted to leave some feedback where I feel my biggest ux impacts were

Downloads:
Download link for the models that zip up everything for delivery
#1847 

Model files:
It'd be nice if files could be broken out by filetype. Images grouped together, lys, stl, etc.
#50 

Alternate version:
It'd be nice if we could designate a model folder, and choose have subfolders in that be variants of a model (supported, options, etc). With a lot of releases coming with a ton of variants, this would let my library stay cleaner
#35 and #1848 

Collections:
Right now collections feel pretty similar to libraries. If models could belong to multiple collections, it would allow for better model browsing imo. It's not really viable to browse and explore by tag, where collections would be great for that. 
#1849

I had some other thoughts, but they escaped me. I'll update here if they come back

**Comment by Floppy** [comment]
Thank you! This is all good stuff, thanks so much for the thoughts. I'll probably separate them out into a few different feature requests.

**Comment by Floppy** [comment]
@Rukongai I've split this ticket up into a few others; where we already had the feature request, I've tagged you on it, and I've created new ones for the other suggestions. Thanks!
