### ISSUE TITLE
Uploaded models get created as root

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1704]
When uploading models, the created folders and files have `root.root` user and group ownership. This is somewhat disturbing, as the app itself should be running using the UID and PID specified in the Dockerfile, so why is it happening?

EDIT: The UID and PID aren't actually set in the Dockerfile. I thought they were.

**Comment by prosthetichead** [comment]
I'm having this issue with all the files and folders created by manyfold being owned by root/root. I can not find anything on how to fix this but noticed on the linked pull request the user should be running as 1000:1000? it seems its not?

**Comment by Floppy** [comment]
Yeah, that PR isn't in yet. At the moment it's using whatever the docker user is. Which is bad. I'm looking at doing a security audit soon so I'll have to resolve this one before that.

**Comment by Floppy** [comment]
Linking #2240 to track the root cause (no pun intended).
