### ISSUE TITLE
Remove extraneous folders created for uploaded models

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1705]
Upload unzips a file into a folder of the same name; if that zipfile also includes a folder structure, you can end up with another folder inside that one with the same name, and all the content inside there. We should collapse these so we don't produce extra weird tags.

**Comment by james-harder** [comment]
Hi, I'm interested in taking a stab at this issue. Is there a way to reproduce the issue?

**Comment by Floppy** [comment]
I think, if you zip a couple of STLs up together, it should work correctly and create a folder with the name of the archive with those STLs inside it. But, if you have those two STLs in a folder and compress THAT, you'll get a folder with the name of the archive, then the folder inside the zip file, then the STLs. The outermost folder won't be picked up as a model, and will be left lying around empty when you organize the model inside it. Does that make sense? I can try to make some sample files if you want.

**Comment by james-harder** [comment]
Thanks, that makes sense! I'll try it out and see if I can make any progress.
