### ISSUE TITLE
Upload single file as model

### ISSUE THREAD

**Issue by gregcohen** [manyfold3d/manyfold#1737]
I love this project, and it's helping me get my 3D prints organized!

I was wondering, is it possible to upload a file other than an archive? I'd like to just upload an STL or 3MF, for example.

**Comment by Floppy** [comment]
No reason why not, I guess! I've wanted to upload a single file to add to a model for a while (normally images), but also you should be able to upload single files to create a new model as well. I'll add it to the list!

**Comment by Floppy** [comment]
> Sometimes I will download something, and all I get is a single STL, and Manyfold wont accept that, so I have to zip my single file to be able to upload it, which is kinda silly.

_Originally posted by @ToasterUwU in https://github.com/manyfold3d/manyfold/issues/1091#issuecomment-1924111936_

**Comment by ns-mglaske** [comment]
+1 for this option!

**Comment by tardisx** [comment]
Agreed - for my use case I'd often upload a single "source of truth" as just an .scad file, and maybe one or two "sample" STL files. But it would be nice to be able to:

* upload a single file to create a model (*or* create a model with no files in it)
* add/delete files from a model arbitrarily (looks like #1091 covers that though)

**Comment by Floppy** [comment]
Hoping to get to this pretty soon 👍🏻

**Comment by RandomLegend** [comment]
Any news on this?

I just discovered this tool and the potential for me is insane! I got literally thousands of models i want to upload, and they are singular models i want to keep seperate in the UI. But having to archive every single one of them first would be a nightmare.

**Comment by Floppy** [comment]
Hopefully soon! If you have them in separate folders on disk at the moment, Manyfold will index them properly, but if you want to upload, you will indeed need this. I'm rewriting the underlying storage engine at the moment, after which I'll probably get to this.

**Comment by RandomLegend** [comment]
yeah but if i have like 20 different models in a single folder, wouldn't manyfold put them in one "Model" in it's database?

As of now i've written a little script that takes every single .stl file i have and creates a folder with the same name and puts it in there. I then move them over to the library. That works well enough now.

**Comment by Floppy** [comment]
Yes, it would. Currently 1 folder == 1 model.

**Comment by mx4k** [comment]
This would be really helpful ad we use Manyfold as an internal share for stl files. Thanks so far.
