### ISSUE TITLE
Server error in activeadmin interface

### ISSUE THREAD

**Issue by deviltuner** [manyfold3d/manyfold#1777]
hello

i uopdate the contenair of manyfold docker and now when i go to the administrator i have the error:

W, [2024-01-29T11:24:03.085989 #1]  WARN -- : You are running SQLite in production, this is generally not recommended. You can disable this warning by setting "config.active_record.sqlite3_production_warning=false".

i think it's because i update the several contenair.... but how do i resolve these error? 
![2024-01-29_23h11_04](https://github.com/manyfold3d/manyfold/assets/54572429/217dde75-c7ac-44fe-9a2d-07d3d5e9e9d1)
thanks a lot

**Comment by Floppy** [comment]
Also reported by @lloydpick in #1778, along with being unable to edit models, which is presumably down to the same cause.

**Comment by Floppy** [comment]
Should be fixed in v0.55.1. Thanks again for reporting!
