### ISSUE TITLE
Full internationalisation support, and first MVP translation

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1786]
* #1785 
* #861 
* #1843
* One of:
  * #1842
  * #1841
  * #1840
  * #1839

NLNet Milestone 1.1

**Comment by ToasterUwU** [comment]
If you want people to help with translation, my native language is German. Would be happy to help

**Comment by Floppy** [comment]
@ToasterUwU I've done all the strings now, I think - if you _do_ fancy having a go, look at https://translation.io/floppy/manyfold/de and we can see how the process works!

Note: there are some repeats, I'm going to rationalise it a bit at some point.

**Comment by ToasterUwU** [comment]
@Floppy Cant access that link.

Asks me to log in first, I use github to log in, then I get a popup saying "Create your first project", I click it away and see the following error behind the now gone modal in a red error box:

>  Invalid project or unauthorized access.

**Comment by Floppy** [comment]
Ah, right, I needed to add you to the project once you'd signed up. Try now?

**Comment by ToasterUwU** [comment]
Ok, im going at it. Some things I kinda hard to know where they will show up, but I will try anyways. 

If I make a comment in there, do you get a ping? Cause I asked a question to you for "Caption" but I'm not sure if it will be an actual ping, or just something you will see if you check.

**Comment by Floppy** [comment]
Not sure yet, I'm new to the tool, so we'll see! Thank you for trying it out :)

**Comment by Floppy** [comment]
No notification that I could see, unfortunately. But, I've replied.

**Comment by ToasterUwU** [comment]
Sounds good, i will add some here and there, and if I have questions I will give you a ping here

**Comment by Floppy** [comment]
Ah, I got a summary email with changes and comments this morning, so that's good!

**Comment by Floppy** [comment]
#1839 is 80% complete, so I'm calling that an MVP and saying this milestone is done.
