### ISSUE TITLE
Docker app does not connect to Postgres after changing container names

### ISSUE THREAD

**Issue by bmp7008** [manyfold3d/manyfold#1796]
In my personal docker-compose setup I have a system for naming and organizing my containers so that I can easily find, edit, stop, restart etc. all of the ones that I'm running on the server. I'd like to change the names of the containers from "app", "db", "redis" to "manyfold", "manyfold_db", "manyfold_redis" (or any other names in anyone else's case) but if I do that, then the main app container is unable to connect to Postgres.

I've tried just cloning the repository and running it out-of-the-box, and that works, but immediately after I run "sed -i 's/app/manyfold/g' docker-compose.yml", then the equivalent for the other two containers, the app no longer starts (I go in and make sure that the sed has only changed the values that I want it to, I just do it for accuracy and speed).

Is the container designed only to work with specific names for the containers?

**Comment by Floppy** [comment]
Hm, that's an interesting one; there certainly shouldn't be any requirement for specific container names. Have you changed DATABASE_URL in the environment to match the new Postgres container name? Could you post your updated compose file?

**Comment by Floppy** [comment]
If you've just done that straight replace, you should have `DATABASE_URL: postgresql://manyfold:password@manyfold_db/manyfold?pool=5` in the environment for `manyfold_app`.

Just to help confirm, my own containers are named in an extremely similar pattern to yours, except with the old `van_dam` app name, so there's definitely no requirement for specific names AFAICT.

**Comment by bmp7008** [comment]
`version: "3"

services:
  manyfold:
    image: ghcr.io/manyfold3d/manyfold:latest
    ports:
      - 3214:3214
    volumes:
      - /path/to/your/libraries:/libraries
    environment:
      DATABASE_URL: postgresql://manyfold:password@manyfold_db/manyfold?pool=5
      SECRET_KEY_BASE: a_nice_long_random_string
      REDIS_URL: manyfold_redis://manyfold_redis:6379/1
      # RAILS_RELATIVE_URL_ROOT: /manyfold Sets the root of the manyfold to /manyfold useful for reverse proxies with nginx
    depends_on:
      - manyfold_db
      - manyfold_redis
    networks:
      - manyfold
    links:
      - manyfold_db
      - manyfold_redis

  manyfold_db:
    image: postgres:15
    volumes:
      - manyfold_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: manyfold
      POSTGRES_PASSWORD: password
    restart: on-failure
    networks:
      - manyfold

  manyfold_redis:
    image: redis:7
    restart: on-failure
    networks:
      - manyfold

volumes:
  manyfold_db_data:


networks:
  manyfold:`

I apologize since I got rid of the compose file(s) that I was using when I was trying this last night, but I redid the one that made me think I was having the problem I was talking about. I tested the one above on the same server and was having the same problem with it.

I also wanted to mention that the way that I'm running the program for testing is by cloning the whole repository, then running the compose file from within the folder (after moving it from docker-compose.example.yml -> docker-compose.yml).

Thanks for the help and the response!

**Comment by Floppy** [comment]
Hm, that looks sensible at first glance... do you have any log output showing the connection error?

**Comment by bmp7008** [comment]
I also want to apologize since I'm pretty new to GitHub and I definitely formatted the code block incorrectly. I thought it'd also be helpful to include the two critical lines of the logs coming out of Docker:

`Preparing database...
rails aborted!
URI::InvalidURIError: the scheme postgresql does not accept registry part: manyfold:password@manyfold_db (or bad hostname?) (URI::InvalidURIError)`

**Comment by bmp7008** [comment]
I know it takes a little bit of time for a Postgres database to start, but if I try the restart about fifteen seconds later I'm still getting the same error. Should I just wait longer? What I thought was a little strange about the problem was that if I did leave the container names intact like they came, everything worked fine on the first try.

**Comment by Floppy** [comment]
Oh, from a bit of googling it looks like underscores might not be valid in hostnames sometimes? Try changing `manyfold_db` to `manyfold-db` and see if that helps? Not sure though, I'm using them in mine...

**Comment by bmp7008** [comment]
Actually, that seems to have fixed it. I didn't know that—I have underscores in most of my other container hostnames, so I'm a little worried now... I apologize that it seems like my question wasn't the most related to the actual software and was more about my usage of Docker—thanks, though!

I guess I'll have to trial-and-error to see what is and is not acceptable. I'll close the thread, at least.

Thanks again!

**Comment by Floppy** [comment]
Well, you're not alone, I've used underscores in mine! I'm not sure why that works but it doesn't in other cases. I guess we all learned something today!

Oh, and you can edit your post if you want to fix that compose file error, in case someone does stumble across it.
