### ISSUE TITLE
[BUG] Version 0.56.0 won't start on New Fresh installation

### ISSUE THREAD

**Issue by mariushosting** [manyfold3d/manyfold#1820]
Caused by:
PG::UndefinedColumn: ERROR:  column problems.ignored does not exist (PG::UndefinedColumn)
LINE 1: SELECT "problems".* FROM "problems" WHERE "problems"."ignore...

No issue if you upgrade from a previous manyfold version like from **0.55.2** to the **0.56.0**
The issue appear only on a **FRESH new installation** that use the :latest tag currently equivalent to the version **0.56.0**

**Comment by Floppy** [comment]
Thanks for the report (and @adobin too). Will investigate and fix asap.

**Comment by Floppy** [comment]
So, migrating from zero locally works ok, but that's using SQLite, so this could be a postgres-specific thing.

**Comment by mariushosting** [comment]
> So, migrating from zero locally works ok, but that's using SQLite, so this could be a postgres-specific thing.

No issue with version 0.55.2
The issue is related only with the version 0.56.0

**Comment by Floppy** [comment]
Having slept on it, I think this is because of the new default scope in `Problem`, which is affecting data migrations. I need to change over from "running every migration" when bootstrapping a new DB, to "loading the schema in one go".

**Comment by Floppy** [comment]
replicated locally with `RAILS_ENV=production bundle exec rails db:prepare:with_data`

**Comment by Floppy** [comment]
And in dev mode too, so it's a difference between the command that docker runs on boot, `bundle exec rails db:prepare:with_data`, and whatever happens inside `bin/dev`.

**Comment by Floppy** [comment]
Ah, yes, `bin/setup` wasn't running `db:prepare:with_data`, just `db:prepare`, so that's one difference. Not the root cause at all, but why my earlier attempt to replicate failed.

**Comment by Floppy** [comment]
Fix released now in v0.56.1. Thanks for reporting ❤️
