### ISSUE TITLE
Can't open problem in admin interface

### ISSUE THREAD

**Issue by Schnuecks** [manyfold3d/manyfold#1832]
**Describe the bug**
unable to open problems in admin interface

**To Reproduce**
1. Go to 'admin'
2. Click on 'problems.'
3. See error

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

GET https://3dprint.home.lan/admin/problems 500 (Internal Server Error)

**Expected behavior**
the problem tab opens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browserchrome,
 - Version [121]

**Comment by Floppy** [comment]
Thanks! I've had this problem for a while, I've got a fix on the back burner in #1783. Thanks for logging it!
