### ISSUE TITLE
Full translation into German

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1839]
German is the 5th most used language on the web according to https://www.statista.com/statistics/262946/most-common-languages-on-the-internet/. @ToasterUwU is helping out with this at the moment. If you'd like to help, sign up on https://translation.io, post your username, and I'll get you set up.

**Comment by beniroquai** [comment]
Happy to help. But how? ;-)

**Comment by Floppy** [comment]
@beniroquai if you register on https://translation.io, and post your username, I'll get you set up!

**Comment by beniroquai** [comment]
Thanks! Did already; Used my github handle - does this work?

**Comment by Floppy** [comment]
OK @beniroquai, I've added you on. You should now be able to go to https://translation.io/floppy/manyfold/de, and see the list of keys that need translating! There's a filter for "untranslated" so you can easily see what's left. Any questions, leave a comment, and I'll respond on there.

**Comment by Mallo321123** [comment]
Can I still Sign up for German? I am a Native.

**Comment by Floppy** [comment]
@Mallo321123 thanks! I've sent you an invite, so you should be good to go! Much appreciated ❤️

**Comment by LucaJunge** [comment]
Hey! I would like to help with german translation, I noticed there are some missing translations :)
My translation.io Username is lucaj

**Comment by Floppy** [comment]
Thanks @LucaJunge, more translators are always welcome! I've added you, you should be able to see the project now.

**Comment by Floppy** [comment]
I've added a link to a [style guide](https://zulip.readthedocs.io/en/latest/translating/german.html) in the main body of this issue, thanks to @LucaJunge asking the question!

**Comment by lefduti** [comment]
Hey! I would like to help. 
My username is lefduti

**Comment by Floppy** [comment]
@lefduti thanks! I've added you, you should be able to add translations now!
