### ISSUE TITLE
Full translation into French

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1840]
French is the 4th most commonly used language on the web according to https://www.statista.com/statistics/262946/most-common-languages-on-the-internet/. If you'd like to volunteer, sign up on https://translation.io, post your username, and I'll get you set up.

**Comment by clepoittevin** [comment]
Hey @Floppy ,

As a french user of the app, i can help you to translate in French :)

My username is clepoittevin

**Comment by Floppy** [comment]
@clepoittevin fantastic, thank you! I've set you up, you should be able to visit https://translation.io/floppy/manyfold/fr and get started!

**Comment by clepoittevin** [comment]
@Floppy It's okay for me :) I started to translate .

**Comment by Andreaj42** [comment]
Hello, 
I'm a French user too, I can help with translation if needed.
My username: andreaj42

**Comment by Floppy** [comment]
@Andreaj42 done! Thanks :)

**Comment by Floppy** [comment]
French was our first 100% translation, thanks everyone. Obviously there's more as time goes on as things get added and change, but I'm closing this specific issue off.
