### ISSUE TITLE
Full translation into Spanish

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1841]
Spanish is the 3rd most commonly used language on the web according to https://www.statista.com/statistics/262946/most-common-languages-on-the-internet/. If you'd like to volunteer, sign up on https://translation.io, post your username, and I'll get you set up.

**Comment by juanjomurga** [comment]
Hi Floppy,

I would like to help you with the Spanish translation.
My username is juanjomurga

Thank you

**Comment by Floppy** [comment]
@juanjomurga fantastic, thank you! I've added you to translation.io, you should see the project over there 👍🏻

**Comment by juanjomurga** [comment]
Hi @Floppy 
I see that there are some words that have not been incorporated correctly. I will review them as soon as possible and update the Translation.io repository
Sorry if this causes you any discomfort.

**Comment by Floppy** [comment]
No worries! It's always the way. I can easily push out a patch release, I expect a few other bugs to get reported in the new version anyway.
