### ISSUE TITLE
Unable to scan libraries

### ISSUE THREAD

**Issue by Rukongai** [manyfold3d/manyfold#1864]
**Describe the bug**
docker build from source - I'm unable to scan libraries using either scan option in the toolbar

Attempting to do so throws the following error in the application logs

```
I, [2024-02-14T09:23:35.625799 #73]  INFO -- : [35200163-2cff-4259-a73e-ed5d002eaeaf] method=GET path=/libraries/scan format=html controller=LibrariesController action=show status=404 allocations=1315 duration=3.07 view=0.00 db=0.92
F, [2024-02-14T09:23:35.626168 #73] FATAL -- : [35200163-2cff-4259-a73e-ed5d002eaeaf]   
[35200163-2cff-4259-a73e-ed5d002eaeaf] ActiveRecord::RecordNotFound (Couldn't find Library with 'id'=scan):
[35200163-2cff-4259-a73e-ed5d002eaeaf]   
[35200163-2cff-4259-a73e-ed5d002eaeaf] app/controllers/libraries_controller.rb:81:in `get_library'
```

**To Reproduce**
1. Clone repo
2. Use Dockerbuild to build docker image, run
3. Add library at setup, attempt to do a scan
4. 404

**Desktop (please complete the following information):**
 - OS: Windows/Docker
 - Browser Firefox/Edge

**Comment by Floppy** [comment]
Ooh interesting; I'll try to replicate. Thanks for the report, it looks like I've broken something, from the log...
