### ISSUE TITLE
No way to delete libraries

### ISSUE THREAD

**Issue by Rukongai** [manyfold3d/manyfold#1866]
**Describe the bug**
This might be operator error, but I can't see any way to delete libraries. I've checked both 0.56.1 and source
I've checked advanced administration, on all tabs
I've checked every where I could click after navigating to the Library on the navigation bar
I've tried going to settings, libraries, and hitting edit on the library I want to remove

**Comment by Floppy** [comment]
I _thought_ it was possible in Advanced Administration; I'll check.

**Comment by arcanescroll** [comment]
I have the same issue, I don't have a Libraries tab in the Advanced Administration.  I did in the older VanDAM release.

**Comment by arcanescroll** [comment]
Here's a screenshot.  Also, Links and Problems just give error messages.  I'm not sure if that's related, but I figured I would mention it just in case.

![fghfgjhhgfhfh](https://github.com/manyfold3d/manyfold/assets/111160566/c05bf3f1-d9a2-48cd-9166-ea647f2e461d)

**Comment by Floppy** [comment]
That's a separate problem, but thanks for noting it :)

**Comment by Floppy** [comment]
Looks like Models and Files are missing too!

**Comment by Floppy** [comment]
This looks like a problem I've caused when adding Pundit and security policies; I'll investigate further.

**Comment by ZwiebelTVDE** [comment]
are there any advances on this?

Currently, there is no way to change a library path or to simply delete a library and create a new one

**Comment by Floppy** [comment]
I'm in the middle of some underlying changes to the permission model that should unblock this soon. At the moment I have a fix, but it breaks some other things, so I need to get that refactoring done before making the change. Not long, I hope!
