### ISSUE TITLE
Renders are not loading for models

### ISSUE THREAD

**Issue by arcanescroll** [manyfold3d/manyfold#1878]
**Describe the bug**
Any time I open a model, the images load fine but the renders just show "Load ()".  If I click them, it changes to "Infinity%".  Eventually the render will load, but I have to go through this every time I open the model.

**Desktop (please complete the following information):**
 - OS: Synology 418play, Windows 10
 - Browser: Firefox 122.0.1

![20240216a](https://github.com/manyfold3d/manyfold/assets/111160566/44ad47ca-d403-4829-b3b5-beb4ad99e820)
![20240216b](https://github.com/manyfold3d/manyfold/assets/111160566/bfde675c-674f-4bad-8815-634f95c74383)

**Comment by Floppy** [comment]
I've replicated this problem locally in dev, so I'll get a fix out soon. Thanks for reporting!

**Comment by Floppy** [comment]
Actually, I thought I had, but it was just my laptop being on low battery and running incredibly slow 😆 

I will investigate though!

**Comment by msrlrocket** [comment]
same thing happening here. I am not quite sure what to do.

**Comment by Floppy** [comment]
I've found the problem, I'll get a bugfix release out for this tomorrow. Thanks for reporting!

**Comment by Floppy** [comment]
The slow loading should be fixed in `v0.57.1`, out now. The click-to-load function itself is intentional, and the size where it switches from automatic to manual can be configured in settings.
