### ISSUE TITLE
I want to make polish translation

### ISSUE THREAD

**Issue by XioR112** [manyfold3d/manyfold#1897]
Hi, I'm native polish speaker and I could make polish translation. My translation.io username is xior112.

**Comment by Floppy** [comment]
Fantastic! Thanks for volunteering! I've enabled `pl`, and you should now be able to log in to https://translation.io/floppy/manyfold/pl and get going!

**Comment by XioR112** [comment]
Hey, translation.io stopped working for me. When clicking the project name I get "You don't have access to any language on this project. " error and when entering through above URL I get "Invalid language for this project. " error.

**Comment by XioR112** [comment]
It works now.

**Comment by Floppy** [comment]
This is in a great state, thanks @XioR112! Obviously there's a few bits more as time goes on as things get added and change, but I'm closing this specific issue off.
