### ISSUE TITLE
Files and archives already present in a folder are not added / recognized

### ISSUE THREAD

**Issue by Kimbaras** [manyfold3d/manyfold#1927]
**Describe the bug**
Basically the files (either single STLs or archives) already present in a folder are not recognized

**To Reproduce**

1. Have a folder with already some STLs or archives
   Eg:
   - /opt/stl (passed on docker-compose as _/opt/stl:/libraries_) which already contains something (eg: /opt/stl/folder1)
2. Add new library from interface
   Based on the example above, it would be /libraries/folder1

**Expected behavior**
The expected behavior on the library add and scan would be for the existing models / archives to be added.

Using docker build 0.57.1 (ae1225a)

**Additional context**
Seems the issue is with exiting models as when uploading a new model / archive, this is uploaded correctly and added to the folder.

Not sure if this is intended behavior or not, in my case I've already have a "library" of about 300+ GB so reimporting the models would be quite painful.

I don't think it's a permission issue as in the mentioned folder, after adding a test model the permissions of the file and folder where the same as the other archive files already present.

**Comment by Floppy** [comment]
Zipfiles won't be picked up, we don't index those on disk, but the STLs that are already there certainly should be.

**Comment by Kimbaras** [comment]
> Have you hit the scan for changes button? I can't remember whether it does it automatically on new library creation or not

Yup, it does automatically when creating a new one, as well as I've tried multiple times to manually scan, it gives the message that the scan is in process but no further updates.

NOTE: the folder I've tried this is a remote share folder (via NFS) so not sure if it just need a lot of time to read the remote location, but I've tried also pointing to a smaller subfolder where there was at least a couple of STLs as well as multiple archives and did not pick anything :/

> Zipfiles won't be picked up, we don't index those on disk

Wait, does this mean that for the existing zips must be uploaded again?
If yes, this is only for existing ones or for any zip not uploaded through manyfold?

Example:
My current setup / library is a NFS shared folder, mounted on a Nextcloud vm, where I uploaded and organized the various STL (by type, scope and so on).
If I was to have an empty folder (on the NFS share) which is mounted by nextcloud AND manyfold and I'd upload a zip through nextcloud, manyfold would pickup that? 
Or zips must be uploaded through manyfold to be processed?

Thanks!

**Comment by Floppy** [comment]
Currently, zips are only processed via the "upload" page. #456 is an open feature request for direct indexing of stuff inside zipfiles, which hopefully I'll get to at some point.

Manyfold's built in scan will only detect files on disk that aren't in zipfiles.

Having said that though, it seems that the scan isn't running in your case. Is the scan button showing a spinner to indicate scanning in progress? If you click on that, it should take you to the current list of scan tasks, and the advanced admin dashboard will show you a count of how many there are. Can you post a screenshot or two of what you see? It's possible the scanner jobs aren't actually running...

**Comment by Kimbaras** [comment]
Ah, that's actually an issue I opened a while ago (when the project was still named VanDAM), nice to see it's planned (and to be fair I think I might have misread your last comment on that one, so my fault there).

Will patiently wait for that then :D 

Regarding the scan, yes, it was showing a spinner but it never ended (probably due to the big remote share?) and if I changed page then it stopped and didn't show nothing.
Will try again as soon as I get the chance and post the results as requested.

Thanks!

**Comment by Floppy** [comment]
Hm, something's not working right there for sure. If the spinner has gone away but nothing's appeared, then it's not doing the right thing.

**Comment by Kimbaras** [comment]
Screenshots incoming...

So, as you said, click on "Scan" button, spinner shows up, clicked again on it, under "Tasks" there is nothing.

Library config
![Schermata 2024-03-04 alle 15 10 14](https://github.com/manyfold3d/manyfold/assets/102742484/52002dc8-c6a6-4e25-a3b0-718081198ca3)

Folder contents
![Schermata 2024-03-04 alle 15 11 18](https://github.com/manyfold3d/manyfold/assets/102742484/ff0a9755-2658-4220-bd58-f16b40d9ec36)

Clicked on "Scan"
![Schermata 2024-03-04 alle 15 11 55](https://github.com/manyfold3d/manyfold/assets/102742484/5193ffa4-2e98-4790-98e9-5eada9b9db58)

Admin interface
![Schermata 2024-03-04 alle 15 12 08](https://github.com/manyfold3d/manyfold/assets/102742484/65b316ae-7198-4ded-accb-47d6ca953a40)

Maaaaaybe the fault may be in the spaces in the library path / name?

**Comment by Floppy** [comment]
Ah, OK, yes. The library path should just be the root of the folder where you keep all your models. So, for instance `/libraries/remote/Horus Heresy`, or even just `libraries/remote`. It won't detect any files in the root of the library, it assumes things are in folders under that. I definitely need to improve the onboarding to explain that better (or at all).

Also: Magnus did nothing wrong

**Comment by Floppy** [comment]
So it's very quickly scanning the library, finding no subfolders, and stopping. That's why you get a scanning spinner but then it disappears.

Hopefully this will all be better explained soon.

**Comment by Kimbaras** [comment]
Ah-a!

Ok, created a new library (btw, the issue #1866 seems to be still present, I can't see any way to delete or edit an existing library) and it worked, it started scanning and displaying the various models in the subfolders.

Just one more question: this means that models in the root folder are not picked up?
Eg: given the library path of `/libraries/remote/Horus Heresy` the models located in the subfolder `Thousand Sons` will be picked up, while files that are "loose" in the root dir will not? Is this correct?

Anyway, question put aside, I believe you can close this one as it was user-misconfiguration and not a real bug / issue

Thanks for the feedback!

**Comment by Floppy** [comment]
Yes, that's right, loose files in the root won't be picked up, mainly because we probably can't really consider them to be one model, so the current structure logic doesn't work. Maybe something that could change in future.
