### ISSUE TITLE
Folder names with [] are shown as empty

### ISSUE THREAD

**Issue by arcanescroll** [manyfold3d/manyfold#1930]
I noticed any folders I have with [ and ] in the folder name are not processed.

For example...
/miniatures/Dragon - Red [updated]/

Shows an entry but there are no files associated with it.

**Comment by Floppy** [comment]
Ooh, that's a fun one! Thanks for reporting it, I'll get a fix out for you this week.

**Comment by Floppy** [comment]
Or even quicker, in fact. I've done a fix (I think), and it's released in v0.57.2. Let me know if it solves your problem!
