### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by ZwiebelTVDE** [manyfold3d/manyfold#1941]
**Is your feature request related to a problem? Please describe.**
It would be great to have a way to change the current localization. My native language is German which is supported but there is no apparent way to change the language to English for a more pleasant UI experience.

**Describe the solution you'd like**
Please add a setting in the user settings  where a user can specify their preferred language

**Describe alternatives you've considered**
Improve/complete German localization but that's more a bandaid than an actual fix

**Additional context**
![image](https://github.com/manyfold3d/manyfold/assets/48917674/0255a61e-3a35-44ed-a169-c99935d935e4)

1. Random English text intPa otherwise German UI
2. Different spelling between "Modells" and "Modelle"

**Comment by Floppy** [comment]
This is a good idea; it uses the browser language by default, but I can imagine it would be helpful to change it manually as well.

We're about 82% complete on the german translation, so hopefully before long we can get it to 100% and fix those consistency problems too, get it fully translated.

**Comment by Floppy** [comment]
(I've changed that "modells" error btw, thanks for pointing it out!)

**Comment by ZwiebelTVDE** [comment]
How can I help with the German localization?

**Comment by Fabaderheld** [comment]
Hi,

to add to this. My browser is set to english still it shows up in german.

regards

Fabian

**Comment by Floppy** [comment]
Oh, that's interesting and unexpected! Could you post a screenshot of your browser language settings?

**Comment by Fabaderheld** [comment]
Ok, interessting

Chrome is set to german but it shows up in english

![image](https://github.com/manyfold3d/manyfold/assets/4440238/e36c0719-a923-4d0d-8a18-3050960c2216)

after I switched it to english, manyfold also switches to english
