### ISSUE TITLE
"invalid byte sequence in UTF-8" when scanning for changes

### ISSUE THREAD

**Issue by SirEdvin** [manyfold3d/manyfold#1950]
**Describe the bug**
I can't run scan for changes, it just fails

**To Reproduce**
1. Create folder with non-ASCII symbol, for example ἀ, like Testἀfolder
2. Go to main page
3. Click on Scan -> Scan for changes
4. See error in task list

**Expected behavior**
Scan finished successfully

**Additional context**

[Log](https://pastebin.com/Et91ABGk) of the failed task

**Comment by Floppy** [comment]
Thanks! I'll get that fixed.

**Comment by Floppy** [comment]
I have found some strange behaviour which I'll fix, but I can't replicate that exact error. What OS and filesystem type are you using?

**Comment by SirEdvin** [comment]
So, I figure out exact issue and it, well, problem with my setup. 
If you run manyfold with NAS storage on system that doens't support utf-8 encoding, it would break like I described. 
Probably, not really ruby related :(

**Comment by Floppy** [comment]
Ah, that would do it! Interestingly though it did throw up some other weird bugs on my filesystem (though perhaps just UI things), so I'll look at those anyway :)

**Comment by Beagon** [comment]
@Floppy I have encountered this issue as well and would like to give some input.

For me, this has to do with running a ZFS partition without the **utf8only** flag. However, I would appreciate it Manyfold wouldn't stop scanning but just mark those files as incompatible/list them as errors so I can manually fix them.

Would be great if that's implemented, for now I run `LC_ALL=C find . -name '*[! -~]*'` as a command to get all faulty folders/files.
