### ISSUE TITLE
Some plural forms seam to be hardcoded

### ISSUE THREAD

**Issue by XioR112** [manyfold3d/manyfold#1983]
Some text uses singular form + s witch doesn't work in other languages.

For example:
![obraz](https://github.com/manyfold3d/manyfold/assets/72562583/421103cc-9843-4ab8-b372-ffa1788e9814)

![obraz](https://github.com/manyfold3d/manyfold/assets/72562583/034597b8-7798-44dc-96d6-d66f94c28286)

**Comment by Floppy** [comment]
Thanks, I've probably missed a pluralize() or two around the place.

**Comment by Floppy** [comment]
The app should know how to properly pluralize things via https://github.com/svenfuchs/rails-i18n. Perhaps I'm not calling things right.

**Comment by Floppy** [comment]
@XioR112 could you give me an example of how you'd pluralize, say, Models? Like, "1 model", "10  models", "100 models"? Rails has a way to represent these things (including many-clause pluralizations like one/few/many/other), so if you can pop me an example, I'll make sure it works then add it to the translation instructions.

**Comment by XioR112** [comment]
singular form - model
ending with 2, 3, 4 with exception of 12, 13, 14 - modele
the rest - modeli

singular form - twórca
ending with 2, 3, 4 with exception of 12, 13, 14 - twórców
the rest - twórców

singular form - biblioteka
ending with 2, 3, 4 with exception of 12, 13, 14 - biblioteki
the rest - bibliotek

**Comment by XioR112** [comment]
Grammatical cases

singular form - mianownik, singular
ending with 2, 3, 4 with exception of 12, 13, 14 - biernik, plural
the rest - dopełniacz, plural

![obraz](https://github.com/manyfold3d/manyfold/assets/72562583/742cdeb2-af76-422e-9d5d-43685a913402)

**Comment by Floppy** [comment]
Fantastic, thanks, I will have a poke around with the translation files and see if can make that work.

**Comment by XioR112** [comment]
I wanted to clarify we use dopełniacz with not only 12, 13 and 14 but every number ending with them.

**Comment by Floppy** [comment]
OK, I think I've resolved this in #2074. There are new keys added to the model names for `one` and `other` pluralizations in german and french, and `one` `few` and `other` for polish. `few` is used for your 2,3,4 case as you can see at https://github.com/svenfuchs/rails-i18n/blob/master/rails/pluralization/pl.rb.

I've added the pluralisations I was sure about, but it will be best to check them over. @Andreaj42 and @ToasterUwU, might you be able to check the translations for your preferred languages? Search for "one" and "other" in the translation.io interface to check the new stuff.

**Comment by XioR112** [comment]
I checked and they aren't available in translation.io interface.

**Comment by Floppy** [comment]
I forgot to add them to English; oops. I'd do that, then hopefully they will turn up. I'll post back when I've done that.

**Comment by Floppy** [comment]
OK, done a sync, and `one` and `other` forms are there now. It's only added the ones that are in the English translation file though, so the `few` form isn't showing up (because English doesn't have it). I'll look at the configuration and check with translation.io how I should be doing that...

**Comment by Floppy** [comment]
Right, I found https://github.com/translation/rails/issues/40 which says that I should have all the pluralization forms in the English file. So, I'll add those.

**Comment by Floppy** [comment]
OK, all models now have keys up on translation.io for all known plural forms. That means there's some redundancy, all languages get all of them, but at least it's all *possible*. Without changing to gettext translations, that's the best we can do.
