### ISSUE TITLE
Statistics aren't translatable

### ISSUE THREAD

**Issue by XioR112** [manyfold3d/manyfold#1984]
There is no way to translate those. Also in Polish we need to use different case depending on number.

You can learn more here:
https://en.wikipedia.org/wiki/Polish_grammar#Numbers_and_quantifiers 

![obraz](https://github.com/manyfold3d/manyfold/assets/72562583/5d83d771-d151-43eb-a584-a67610b44893)

**Comment by Floppy** [comment]
It should be coming from the name of the rails models; I'll have a look at the pluralisation of those, see what I've missed. Rails i18n should be able to cope with it.

**Comment by Floppy** [comment]
They may still suffer from #1983, but the root words should now be right.
