### ISSUE TITLE
Can't disable User signup

### ISSUE THREAD

**Issue by Popoboxxo** [manyfold3d/manyfold#1985]
**Describe the bug**

![image](https://github.com/manyfold3d/manyfold/assets/11631395/feeb3272-b7cf-47d4-bb53-0b17ee625e16)

Deactivated User-SignUp via env.
But registration is furthermore possible: (Tested with a new Mail/Name e.g.)

![image](https://github.com/manyfold3d/manyfold/assets/11631395/a6a96e16-4a5a-4473-8a82-c0ab2a92515d)

I tried "disable", "disabled", "false"

**To Reproduce**
- Change Docker-Compose file und restart the server

**Expected behavior**
- Configuration = Disabled i excpect to Disable this feature

Used Docker-Compose (+Ansible)

version: "3"

services:
  app:
    image: ghcr.io/manyfold3d/manyfold:{{ docker.manyfold.tag }}
    volumes:
      - app_data:/libraries
    environment:
      - DATABASE_URL=postgresql://manyfold:{{manyfold_secret.db.password}}@manyfold-db/manyfold?pool=5
      - SECRET_KEY_BASE={{manyfold_secret.app.secret}}
      - REDIS_URL=redis://manyfold-redis:6379/1
      - MULTIUSER=enabled
      - REGISTRATION=false
      # For details of other optional environment variables, including features such
      # as multiuser mode, visit https://manyfold.app/sysadmin/configuration.html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manyfold.rule=Host(`{{ domain.manyfold }}.{{ domain.root }}`)"
      - "traefik.http.routers.manyfold.entrypoints=https"
      - "traefik.http.routers.manyfold.tls.certresolver=letsencrypt"
      - "traefik.http.routers.manyfold.service=manyfold"
      - "traefik.http.services.manyfold.loadbalancer.server.port=3214"
    depends_on:
      - db
      - redis
    networks:
      - web
    links:
      - db
      - redis

...... (db/redis irelevant)

**Comment by Floppy** [comment]
Ooh, thank you. Did you have it enabled for a while and now can't turn it off? What happens if you remove the variable completely?

**Comment by Popoboxxo** [comment]
Hey,

First, i Set it Up without the variable (several times because of docker Network Problems), after the Initial Setup, i added the Multiuser Variable. After restarting, the Multiuser Support was enabled including the the enabled Registration (Settings UI) (without adding the Variable). So far I haven't been able to turn the feature off.

I'm assuming "disabled" would be the correct attribute value, right?

**Comment by Floppy** [comment]
It should be off for everything except "enabled". But, at one point I did make a mistake with that text on the settings page, let me check I didn't fix it in the wrong direction! Does the signup page actually work?

**Comment by Popoboxxo** [comment]
The Page works perfectly!

**Comment by Floppy** [comment]
Thanks - I've obviously done something silly. I'll look into it!

**Comment by Floppy** [comment]
Yeah, OK, managed to sit down with the code already and I can see my first silly mistake already, which explains the UI error on the settings page.
