### ISSUE TITLE
Upload File into existing Model

### ISSUE THREAD

**Issue by Bastilms** [manyfold3d/manyfold#2032]
**Is your feature request related to a problem? Please describe.**
In order to add a File into a existing Model, for example a picture or an updated version, I have to copy the file into the folder on the server and scan for changes.

**Describe the solution you'd like**
It would be nice to have an Upload Button inside the Model in order to upload a file via the GUI.

**Comment by Floppy** [comment]
Definitely something I want to add. There's already a feature request open for it in #1091, so I'll close this as a duplicate, but rest assured it's definitely on my list.
