### ISSUE TITLE
Problem tab - select all doesn't work

### ISSUE THREAD

**Issue by Schnuecks** [manyfold3d/manyfold#2142]
**Describe the bug**
Problem tab - select all doesn't work

**To Reproduce**
1. Go to 'Admin Inteface'
2. Click on 'Problems'
3. Click on first checkbox to select all'
4. Doesn't select all files

**Expected behavior**
If i click on the checkbos all files get selected

**Comment by Floppy** [comment]
I've had a look at this, and noticed that it doesn't actually work on ANY of the pages. So, that's odd. More investigation to follow.

**Comment by Floppy** [comment]
Inspired by exploration of #891, I wonder if this could be an active_admin javascript loading problem...
