### ISSUE TITLE
3MF conversion can create invalid files on Windows because of filename rules

### ISSUE THREAD

**Issue by TXJustin** [manyfold3d/manyfold#2143]
**Describe the bug**
Using the Convert to 3MF button on a STL creates a 3MF file.  Trying to use the resulting file with Bambu Studio returns a failure that there is no geometry data.  I know Bambu uses 3MF spec-production and thought that might be a problem but received the same error with Orca Slicer which is using spec-core.  Then I looked in the file itself and it's pretty much empty with its entire contents being:
C:.
│   [Content_Types].xml
│
└───_rels
        .rels

**To Reproduce**
To rule out a specific STL source file causing the issue I tried others, and have the same result.
1. Go to any STL file in the library
2. Click on Convert to 3MF
3. No error is produced, process appears to complete successfully

**Expected behavior**
Resulting 3MF should contain necessary data.

**Screenshots**

Manyfold v0.65 is running as a container on
Ubuntu 22.04.4 LTS
Docker CE 26.1.1

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Vivaldi 6.5

**Additional context**

**Comment by Floppy** [comment]
Ooh, that's not right. I assume the converted 3MF file doesn't show anything in Manyfold itself either? Could you attach one of your original files and the converted result so I can take a closer look?

I definitely get geometry converted over here (I just tried it), and can load it into Lychee fine, so it's not *completely* broken; something odd is happening somewhere...

**Comment by Floppy** [comment]
Is that a broken one? Because the 3MF displays in Manifold for me, loads into Lychee fine, and when I unzip the 3MF itself it includes a model...

<img width="884" alt="Screenshot 2024-05-06 at 16 30 48" src="https://github.com/manyfold3d/manyfold/assets/3565/41d647fb-e5dd-4bfd-a543-c2a83875d6dd">
<img width="1206" alt="Screenshot 2024-05-06 at 16 30 59" src="https://github.com/manyfold3d/manyfold/assets/3565/43870d82-d9ec-4cbd-a4b7-c71911acbd1a">
<img width="228" alt="Screenshot 2024-05-06 at 16 32 29" src="https://github.com/manyfold3d/manyfold/assets/3565/b6f3fe7d-7a18-4355-b57e-6775f8059b52">

**Comment by Floppy** [comment]
The only thing I can think of is that the filename of the model there has the angle brackets and hash in it; could that be confusing things perhaps? What filesystem is your library on?

**Comment by TXJustin** [comment]
OK, it's something on my end.  I had not checked, but on the Linux server running Manyfold I see the 3D data, but once it gets to Windows that data vanishes.  I'm doing some oddball Linux OneDrive synching in the middle of this to a named docker volume that I then present to Manyfold and I'm suspecting that as the file starts to be written the other container is interfering.  Underlying EXT4 and docker volumes - pretty sure neither is intended for multiple attachments to a file, so I'll have to set things up different.

False-alarm Monday.   :neutral_face:
Appreciate the quick response and insight.

**Comment by TXJustin** [comment]
Here's what I get, just so you know I'm not blind -

![image](https://github.com/manyfold3d/manyfold/assets/39938760/378f3972-9c0f-439c-9848-3a241f678570)

**Comment by Floppy** [comment]
Aha, that makes sense then! Right, I should make sure those filenames don't have anything weird in them in that case. 

Interesting that the filesystem constraint also stops it working in the apps like OrcaSlicer, you'd think the importer wouldn't care if it wasn't actually extracting them to disk. OK, well I should be able to fix this pretty quick and get a release out for you soon. 👍🏻 

Thanks for the report and the debugging info!

**Comment by Floppy** [comment]
This should be fixed now in #2173, and I'll do a patch release shortly, which will be v0.66.2
