### ISSUE TITLE
CORS error using reverse proxy

### ISSUE THREAD

**Issue by dpinse** [manyfold3d/manyfold#2166]
**Describe the bug**
I get a CORS origin error when using HAproxy for SSL transmission, is there a config I can update or a way I can pass the original http header instead?

[23b0a769-e5b9-4edf-bbd2-f2f01078e75c] ActionController::InvalidAuthenticityToken (HTTP Origin header (https://helloworld.com) didn't match request.base_url (http://helloworld.com)):

**Comment by Floppy** [comment]
I need to have a proper look into how the app deals with SSL at some point, but perhaps [this comment](https://github.com/rails/rails/issues/22965?ref=firsttiger.com#issuecomment-169956605) might solve your issue? It's got some more headers to configure in the proxy...

**Comment by dpinse** [comment]
Indeed, I was able to resolve this by setting the request headers in HAproxy. Added the snippet for any folks who many need. Closing...

```
http-request set-header X-Forwarded-Ssl on
http-request set-header X-Forwarded-Port 443
http-request set-header X-Forwarded-Host "YOUR_DOMAIN"
```

**Comment by Floppy** [comment]
Oh, that's superb. I should add this to the documentation on the website.
