### ISSUE TITLE
Ability to download all files in a model

### ISSUE THREAD

**Issue by ZoesDev** [manyfold3d/manyfold#2204]
**Is your feature request related to a problem? Please describe.**
Like on thangs, thingiverse, printables. it would be nice to be able to have a  button to redownload the files as a zip or other file to make it easy to use again. Some of the models I have, have over 60 parts and it is time consuming to have to click each one to download.

**Describe the solution you'd like**
Have a button somewhere in the model page that lets you download all files in that set. This can be done on demand or reusing the upload file we use to upload the files into the database.

**Describe alternatives you've considered**

**Additional context**
This could even be as simple as keeping the original compressed file around and linking to that. yes it would take up more space but for most I do not see it being as to much data.

**Comment by Floppy** [comment]
This is definitely on the TODO list - we already have a feature request open for it (#1847), so I'll mark this as a duplicate if that's ok ❤️
