### ISSUE TITLE
Select models to be viewed without an account

### ISSUE THREAD

**Issue by Ikarias** [manyfold3d/manyfold#2220]
Manyfold can be set to multi-user.
"Not logged in" is not an option however.

Would be a real addition if we could select models to be used in a "public" account for sharing/showcasing.

**Comment by Floppy** [comment]
Absolutely. #2192 covers this so I'll close this as a duplicate, but it's definitely something I want to add.

**Comment by Floppy** [comment]
Reopening this as #2192 is more focused on partly visible models, whereas this is a more general request for a permission system (which is happening in #2588)

**Comment by ch0ccyra1n** [comment]
How do I actually go about making a model public?
