### ISSUE TITLE
Error deleting models caused by nonexistent tag

### ISSUE THREAD

**Issue by bbcisdabomb** [manyfold3d/manyfold#2284]
I uploaded a zip full of zips to see if that would work. It did but as I was cleaning up the pages I have two pages with no model files that I can't delete. Clicking the delete button gives me the warning popup "This will delete files" and when I click OK I get an error page, "The page you were looking for doesn't exist."

I have tried recreating the folders Manyfold says it's looking for but it didn't change anything. I get the same error page and the folder isn't deleted on my drive.

I'm running the container on latest Docker, installed this week, on Windows 10, and accessing it from Firefox on Windows 10.

**Comment by Floppy** [comment]
Thanks! To be clear, you're trying to delete the *model* from the model page itself? And that model has no files in it? Can you paste the path of both the model page you're on, and the 404 page? And can you see anything in the log, in the advanced admin area?

**Comment by bbcisdabomb** [comment]
Please excuse my wordiness, I'm trying to make sure I give you all the info I can.

I'm trying to delete the entire model from the model page, with no files. This was a zip of Twin Goddess Miniatures' sculpts of Baldur's Gate 3 characters given to me by a friend so I can print them off. Here I'm trying to delete Ashton the Vampire Aristocrat straight from the Models page located at [server]/models
![image](https://github.com/manyfold3d/manyfold/assets/3829487/67d3eb74-bf08-49e9-91af-5618a1e5e709)

I can open Ashton's page and I see no files, but it does have tags and is located in the correct collection. The page is located at [server]/libraries/1/models/12

I hit the trash button, click Okay on the popup, and I get the following error page located at [server]/libraries/1/models/12
![image](https://github.com/manyfold3d/manyfold/assets/3829487/12b79059-d051-4243-8d6e-ba04de32cd15)

Checking the admin log, which I didn't even realize was available so thank you for telling me, I see the following at the bottom:
I, [2024-06-19T22:58:16.167091 #120]  INFO -- : [7f09e2a4-818b-49b1-91e5-90162192c617] {"method":"GET","path":"/libraries/1/models/11/model_files/42.jpg","format":"jpeg","controller":"ModelFilesController","action":"show","status":200,"allocations":4936,"duration":19.4,"view":0.0,"db":3.99,"@timestamp":"2024-06-19T22:58:16.166Z","@version":"1","message":"[200] GET /libraries/1/models/11/model_files/42.jpg (ModelFilesController#show)"}
I, [2024-06-19T23:00:50.382296 #120]  INFO -- : [3ecde4a7-663c-44d2-a639-d559e479ea17] {"method":"DELETE","path":"/libraries/1/models/12","format":"html","controller":"ModelsController","action":"destroy","status":404,"allocations":10391,"duration":57.34,"view":0.0,"db":17.26,"@timestamp":"2024-06-19T23:00:50.382Z","@version":"1","message":"[404] DELETE /libraries/1/models/12 (ModelsController#destroy)"}
F, [2024-06-19T23:00:50.386826 #120] FATAL -- : [3ecde4a7-663c-44d2-a639-d559e479ea17]   
[3ecde4a7-663c-44d2-a639-d559e479ea17] ActiveRecord::RecordNotFound (Couldn't find ActsAsTaggableOn::Tag with 'id'=19):
[3ecde4a7-663c-44d2-a639-d559e479ea17]   
[3ecde4a7-663c-44d2-a639-d559e479ea17] app/models/model.rb:70:in `delete_from_disk_and_destroy'
[3ecde4a7-663c-44d2-a639-d559e479ea17] app/controllers/models_controller.rb:121:in `destroy'
[3ecde4a7-663c-44d2-a639-d559e479ea17] app/controllers/application_controller.rb:42:in `switch_locale'

I might be able to use the admin buttons to force delete the models but I'll avoid doing that in case you want me to try anything else to whittle down how this bug came about.

Thanks!

**Comment by Floppy** [comment]
Ah, that's interesting, it's actually having a problem removing the associated tag, which is strange but I've heard of once before. Interesting. Try editing the model to remove all the tags first, then it might delete OK?

**Comment by Floppy** [comment]
Perfect response BTW, nothing wrong with wordiness in bug reports ❤️

**Comment by bbcisdabomb** [comment]
Removing the tags and deleting worked. I wonder if part of it was because I was trying to mass delete everything in one tag and it got confused.

In any case, looks like it's resolved. Thanks!

**Comment by Floppy** [comment]
Great! I'm going to reopen and rename the issue, so that I remember to take a look at and fix the underlying problem, seeing as this is the second time I've heard of it!
