### ISSUE TITLE
App strange behaviour after upload completes

### ISSUE THREAD

**Issue by aneurinprice** [manyfold3d/manyfold#2307]
**Describe the bug**
After uploading a zipped model (as normal), the app throws the "We're sorry, but something went wrong" page.

After some time, the app goes back to normal.
Eventually, the uploaded model will appear in app.

I think this may be related to the scanning of the mesh rather than the uploading.

**To Reproduce**
1. Go to 'Upload'
2. Click on 'Browse'
3. Select Model Zip
4. Upload (Scan file after upload enabled)
5. Wait for upload to complete
6. Refresh page, Observe error.

**Expected behavior**
Upload should complete as expected and the app should not break.

**Screenshots**

![image](https://github.com/manyfold3d/manyfold/assets/46961848/9a22727b-b3b5-4236-9663-8250137c67a0)

![image](https://github.com/manyfold3d/manyfold/assets/46961848/5dbf7513-8014-422f-800d-4ce7a3a41805)

![image](https://github.com/manyfold3d/manyfold/assets/46961848/906b68f4-0c23-40c9-ae64-b56d08c19fc1)

In the above image, you can see this in action. I am somewhat surprised by the sudden increase in memory usage.... however this is below the limit I have set (8gb) so Im not thinking that it is related to compute resources.

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Firefox + Safari]
 - Version [172.0]

**Additional context**
[Explore-logs-2024-06-25 15_08_23.txt](https://github.com/user-attachments/files/15972724/Explore-logs-2024-06-25.15_08_23.txt)

**Comment by Floppy** [comment]
Does this happen every time for you? I'm just about to rewrite the entire uploader...

**Comment by aneurinprice** [comment]
It's only started happening since 0.69.0. No changes to database/redis.

Only other change I have made is my database connection pools.... but I think that is unrelated.

**Comment by Floppy** [comment]
OK, I can see some odd behaviour on my own instance, something's off. Thanks for the report, I'll look into it asap.

**Comment by aneurinprice** [comment]
Let me know if you would like any more information/metrics/testing.

**Comment by Floppy** [comment]
Hm, no, the strange thing on my instance was just m being confused by accidentally uploading something in the wrong place. I've done a bunch of uploads and I can't replicate this behaviour... any chance you could try again, turn *off* scan after upload, then when you get the error, paste the log details? I think all I can see in there is the job failures (which are also strange, but not what I'm looking for initially).

**Comment by Floppy** [comment]
I've seen some odd stuff in my development instance, but then again I'm changing upload/file handling a lot in there at the moment so it might be that. Are you definitely running the v0.69.0 release version? Because I can't seem to get it to break on that tag...

**Comment by Floppy** [comment]
So, at version 162c5b6, after the Rails version bump to 7.1, it seems more vulnerable to database pool exhaustion, probably because Redis now uses a connection pool as well. This can cause errors on the activity page, could also affect *any* page because of the scan button check on the queue state, and could cause errors that look like mesh load errors. That all looks consistent with what you see, so I'd be very interested to know if you're on an unreleased version a bit above v0.69.0.

Obviously I still need to deal with all that though, because this code will be in the next release :)

**Comment by aneurinprice** [comment]
Here are the logs you were after.

```
9:32 worker.1 | 2024-06-28T14:29:32.814Z pid=39 tid=zdr class=Analysis::AnalyseModelFileJob jid=403ee7b41a73c80de822c732 INFO: start
14:29:32 worker.1 | 2024-06-28T14:29:32.815Z pid=39 tid=zdr class=Analysis::AnalyseModelFileJob jid=403ee7b41a73c80de822c732 INFO: Performing Analysis::AnalyseModelFileJob (Job ID: 89b14eb4-0c41-4f8a-9874-92b15ff32f0b) from Sidekiq(analysis) enqueued at 2024-06-28T14:29:32Z with arguments: 7388
14:29:32 worker.1 | 2024-06-28T14:29:32.827Z pid=39 tid=zh3 class=Analysis::AnalyseModelFileJob jid=ab5ea9d23d40f09623797577 INFO: start
14:29:32 worker.1 | 2024-06-28T14:29:32.827Z pid=39 tid=zh3 class=Analysis::AnalyseModelFileJob jid=ab5ea9d23d40f09623797577 INFO: Performing Analysis::AnalyseModelFileJob (Job ID: 1765ebd5-60a1-4efe-9179-661a8c90c7db) from Sidekiq(analysis) enqueued at 2024-06-28T14:29:32Z with arguments: 7392
14:29:32 worker.1 | 2024-06-28T14:29:32.830Z pid=39 tid=zj7 class=Analysis::AnalyseModelFileJob jid=50198764d73ffdd59d66e8e1 INFO: start
14:29:32 worker.1 | 2024-06-28T14:29:32.831Z pid=39 tid=zj7 class=Analysis::AnalyseModelFileJob jid=50198764d73ffdd59d66e8e1 INFO: Performing Analysis::AnalyseModelFileJob (Job ID: c4f47687-73b7-4e55-8c0b-c2b10ebdf7aa) from Sidekiq(analysis) enqueued at 2024-06-28T14:29:32Z with arguments: 7395
14:29:32 worker.1 | 2024-06-28T14:29:32.834Z pid=39 tid=zl3 class=Analysis::AnalyseModelFileJob jid=c5c2b672b443f9221f6f0bfb INFO: start
14:29:32 worker.1 | 2024-06-28T14:29:32.834Z pid=39 tid=zl3 class=Analysis::AnalyseModelFileJob jid=c5c2b672b443f9221f6f0bfb INFO: Performing Analysis::AnalyseModelFileJob (Job ID: cddd3e31-f8c8-404d-86a0-3e3a3d00c79a) from Sidekiq(analysis) enqueued at 2024-06-28T14:29:32Z with arguments: 7397
14:29:32 worker.1 | 2024-06-28T14:29:32.841Z pid=39 tid=zkr class=Analysis::AnalyseModelFileJob jid=1bca0f9f03ce2910b1e34d4d INFO: start
14:29:32 worker.1 | 2024-06-28T14:29:32.841Z pid=39 tid=zkr class=Analysis::AnalyseModelFileJob jid=1bca0f9f03ce2910b1e34d4d INFO: Performing Analysis::AnalyseModelFileJob (Job ID: ff4d780e-e30b-4d8f-9129-1fbe527ecbc6) from Sidekiq(analysis) enqueued at 2024-06-28T14:29:32Z with arguments: 7390
14:29:32 worker.1 | 2024-06-28T14:29:32.876Z pid=39 tid=zdr class=Analysis::AnalyseModelFileJob jid=403ee7b41a73c80de822c732 INFO: Performed Analysis::AnalyseModelFileJob (Job ID: 89b14eb4-0c41-4f8a-9874-92b15ff32f0b) from Sidekiq(analysis) in 61.17ms
14:29:32 worker.1 | 2024-06-28T14:29:32.877Z pid=39 tid=zdr class=Analysis::AnalyseModelFileJob jid=403ee7b41a73c80de822c732 elapsed=0.063 INFO: done
14:29:32 worker.1 | 2024-06-28T14:29:32.884Z pid=39 tid=zh3 class=Analysis::AnalyseModelFileJob jid=ab5ea9d23d40f09623797577 INFO: Performed Analysis::AnalyseModelFileJob (Job ID: 1765ebd5-60a1-4efe-9179-661a8c90c7db) from Sidekiq(analysis) in 57.06ms
14:29:32 worker.1 | 2024-06-28T14:29:32.884Z pid=39 tid=zh3 class=Analysis::AnalyseModelFileJob jid=ab5ea9d23d40f09623797577 elapsed=0.058 INFO: done
14:29:32 worker.1 | 2024-06-28T14:29:32.886Z pid=39 tid=zj7 class=Analysis::AnalyseModelFileJob jid=50198764d73ffdd59d66e8e1 INFO: Performed Analysis::AnalyseModelFileJob (Job ID: c4f47687-73b7-4e55-8c0b-c2b10ebdf7aa) from Sidekiq(analysis) in 55.02ms
14:29:32 worker.1 | 2024-06-28T14:29:32.886Z pid=39 tid=zj7 class=Analysis::AnalyseModelFileJob jid=50198764d73ffdd59d66e8e1 elapsed=0.055 INFO: done
14:29:32 worker.1 | 2024-06-28T14:29:32.888Z pid=39 tid=zl3 class=Analysis::AnalyseModelFileJob jid=c5c2b672b443f9221f6f0bfb INFO: Performed Analysis::AnalyseModelFileJob (Job ID: cddd3e31-f8c8-404d-86a0-3e3a3d00c79a) from Sidekiq(analysis) in 54.34ms
14:29:32 worker.1 | 2024-06-28T14:29:32.889Z pid=39 tid=zl3 class=Analysis::AnalyseModelFileJob jid=c5c2b672b443f9221f6f0bfb elapsed=0.055 INFO: done
14:29:32 worker.1 | 2024-06-28T14:29:32.890Z pid=39 tid=zkr class=Analysis::AnalyseModelFileJob jid=1bca0f9f03ce2910b1e34d4d INFO: Performed Analysis::AnalyseModelFileJob (Job ID: ff4d780e-e30b-4d8f-9129-1fbe527ecbc6) from Sidekiq(analysis) in 48.8ms
14:29:32 worker.1 | 2024-06-28T14:29:32.890Z pid=39 tid=zkr class=Analysis::AnalyseModelFileJob jid=1bca0f9f03ce2910b1e34d4d elapsed=0.049 INFO: done
14:29:33 rails.1  | 2024-06-28T14:29:33.424Z pid=95 tid=z3b INFO: Sidekiq 7.2.4 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://manyfold-redis-master:6379/1"}
```

This was one upload with `Scan After Upload: true` and `Scan After Upload: false`.

![Screenshot 2024-06-28 at 15-36-13 Manyfold](https://github.com/manyfold3d/manyfold/assets/46961848/9456c6f4-8274-4c45-8343-4df760b13010)


This is 100% with the correct container image:

```
  containers:
  - env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: MAX_FILE_UPLOAD_SIZE
      value: "5368709120"
    - name: MAX_FILE_EXTRACT_SIZE
      value: "5368709120"
    - name: DATABASE_CONNECTION_POOL
      value: "64"
    - name: DATABASE_HOST
      value: manyfold-postgresql
    - name: DATABASE_USER
      value: manyfold
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: manyfold-postgresql
    - name: DATABASE_NAME
      value: manyfold
    - name: SECRET_KEY_BASE
      value: <redacted>
    - name: REDIS_URL
      value: redis://manyfold-redis-master:6379/1
    image: ghcr.io/manyfold3d/manyfold:0.69.0
    imagePullPolicy: IfNotPresent
    name: manyfold
    ports:
    - containerPort: 3214
      name: http
      protocol: TCP
    resources:
      limits:
        memory: 8Gi
      requests:
        memory: 4Gi
        ```

Is there anything else you'd like me to try?

**Comment by Floppy** [comment]
Hm, that's not showing anything particularly useful, that's a pity. At the moment the best thing I can suggest is upgrading to v0.70.0 when it releases in a day or two; the uploading has been almost completely rewritten, which will hopefully solve your problem.

**Comment by aneurinprice** [comment]
After doing some manual cleaning up of broken models (From the previous version), this issue does now seem to be fixed. Thank you for sorting this one!

**Comment by Floppy** [comment]
Fantastic news ❤️
