### ISSUE TITLE
PG::ConnectionBad: could not translate host name "db" to address: Name does not resolve (PG::ConnectionBad)

### ISSUE THREAD

**Issue by kf0cqx** [manyfold3d/manyfold#2308]
Sorry to bug you over something likely super simple, but I cannot get it to work on my unraid install at all so far. I followed the docker templates and copied all of the settings that were defaulted on all three containers. Love the idea of this container, the error it continually throws is below.

![issue](https://github.com/manyfold3d/manyfold/assets/173872723/2c342aa5-f68a-4fb2-9c03-150308ea4860)

PG::ConnectionBad: could not translate host name "db" to address: Name does not resolve (PG::ConnectionBad)

**Comment by Floppy** [comment]
Could you paste your docker-compose config? With personal information removed, of course. Looks like something's off in the container naming.

**Comment by feroxib** [comment]
are you sure that the hostname db exists? (your postgres database is called "db")
please confirm that you put both docker containers (manifold & PG) into one docker-subnet. docker can only connect containers by their label if they're in a docker network
as far as I know bridge host etc will not work.

alternatively give your database a fixed IP and replace content of the pg-databse hostname with this IP.

**Comment by Floppy** [comment]
Ah, I didn't initially spot this was on unraid - looks like @feroxib has found a couple of issues with the unraid template in #2309 - that might help you out while I improve it.

**Comment by kf0cqx** [comment]
> are you sure that the hostname db exists? (your postgres container is called "db") please confirm that you put both docker containers (manifold & PG) into one docker-subnet. docker can only connect containers by their label if they're in a docker network as far as I know bridge host etc will not work.
> 
> alternatively give your database a fixed IP and replace content of the pg-databse hostname with this IP.

For some reason the custom network I created for this is not allowing me to set static IPs. "user specified IP address is supported only when connecting to networks with user configured subnets".

All three dockers are in their own network called "manyfold", also yes the hostname db does exist.

**Comment by kf0cqx** [comment]
Got it working, now just need to sort out file path as libraries aren't working quite the way I expected.

**Comment by BRAYDIN72** [comment]
How did you get it to fix? Mine is doing the same thing. They are all on the same network 172.17.0.X the postgres docker is labled db but I get

> Illegal option -p
> sh: lspci: not found
> Illegal option -p
> sh: lspci: not found
> Executing database url substitution hack
> DATABASE_USER=manyfold
> GIT_SHA=cf130a046fe7e31119016bdf3dabc5f4ba50a6fa
> HOSTNAME=897d23c2fc25
> SHLVL=1
> PORT=3214
> HOME=/root
> DATABASE_NAME=manyfold
> HOST_OS=Unraid
> BUNDLE_APP_CONFIG=/usr/local/bundle
> PGID=100
> RUBY_DOWNLOAD_URL=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.1.tar.xz
> RUBY_VERSION=3.3.1
> RACK_ENV=production
> PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> LANG=C.UTF-8
> PUID=99
> HOST_HOSTNAME=Tower
> GEM_HOME=/usr/local/bundle
> RAILS_ENV=production
> SECRET_KEY_BASE=***********************************
> RUBY_DOWNLOAD_SHA256=0686941a3ec395a15ae2a852487b2a88e5fb8a5518e188df00d8d1bb71a6349b
> HOST_CONTAINERNAME=Manyfold
> RAILS_SERVE_STATIC_FILES=true
> PWD=/usr/src/app
> DATABASE_PASSWORD=password
> REDIS_URL=redis://redis:6379/1
> TZ=America/Chicago
> BUNDLE_SILENCE_ROOT_WARNING=1
> NODE_ENV=production
> DATABASE_HOST=db
> APP_VERSION=0.71.0
> DATABASE_URL appears to be empty, proceeding with modular string generation
> Required variables check passed
> Preparing database...
Followed by 
**> PG::ConnectionBad: connection to server at "143.244.220.150", port 5432 failed: Operation timed out (PG::ConnectionBad)**
Not sure where its getting the 143.244.220.150 part
Please help me Obi-Wan Kenobi

**Comment by kf0cqx** [comment]
> How did you get it to fix? Mine is doing the same thing. They are all on the same network 172.17.0.X the postgres docker is labled db but I get
> 
> > Illegal option -p
> > sh: lspci: not found
> > Illegal option -p
> > sh: lspci: not found
> > Executing database url substitution hack
> > DATABASE_USER=manyfold
> > GIT_SHA=cf130a046fe7e31119016bdf3dabc5f4ba50a6fa
> > HOSTNAME=897d23c2fc25
> > SHLVL=1
> > PORT=3214
> > HOME=/root
> > DATABASE_NAME=manyfold
> > HOST_OS=Unraid
> > BUNDLE_APP_CONFIG=/usr/local/bundle
> > PGID=100
> > RUBY_DOWNLOAD_URL=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.1.tar.xz
> > RUBY_VERSION=3.3.1
> > RACK_ENV=production
> > PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> > LANG=C.UTF-8
> > PUID=99
> > HOST_HOSTNAME=Tower
> > GEM_HOME=/usr/local/bundle
> > RAILS_ENV=production
> > SECRET_KEY_BASE=***********************************
> > RUBY_DOWNLOAD_SHA256=0686941a3ec395a15ae2a852487b2a88e5fb8a5518e188df00d8d1bb71a6349b
> > HOST_CONTAINERNAME=Manyfold
> > RAILS_SERVE_STATIC_FILES=true
> > PWD=/usr/src/app
> > DATABASE_PASSWORD=password
> > REDIS_URL=redis://redis:6379/1
> > TZ=America/Chicago
> > BUNDLE_SILENCE_ROOT_WARNING=1
> > NODE_ENV=production
> > DATABASE_HOST=db
> > APP_VERSION=0.71.0
> > DATABASE_URL appears to be empty, proceeding with modular string generation
> > Required variables check passed
> > Preparing database...
> > Followed by
> > **> PG::ConnectionBad: connection to server at "143.244.220.150", port 5432 failed: Operation timed out (PG::ConnectionBad)**
> > Not sure where its getting the 143.244.220.150 part
> > Please help me Obi-Wan Kenobi

I went with using default names that Postgres uses and just changed the Manyfold template to be the same. For some reason Postgres wasn't making the new DB that I was trying to specify.

**Comment by BRAYDIN72** [comment]
I switched the network type to wg0 and it connected, but now I have no webUI in the log it says

>  * Listening on http://0.0.0.0:3214
The webUI option says 192.168.1.37:3214 but just times out

**Comment by feroxib** [comment]
can you get into your docker container manyfold by doing
docker exec -it manyfold bash

and then do a simple ping db or dig db
this should give you an indication of if it sees your postgres container 

if your database does not exist on postgres get a UI like cloudbeaver, adminer, and the likes.

connect to postgres (double check these SQL statements online for syntax and mistakes)
 do a:
 create user '...' with password '...';
create database '...';
Grant all privileges on '...' to '...';
reload!

and then you should be able to connect to the database with your A) UI and B) manyfold container

**Comment by feroxib** [comment]
and for anyone who asks why the UI?

my personal opinion:

"I hate SQL"
"I like a good UI"
"I like doing things that I hate on something that I like"

**Comment by BRAYDIN72** [comment]
I ended up just putting the IP for that and redis into the template instead said host name. It came up after that, not sure why the container resolves db and redis incorrectly.  It resolves db and redis both as 143.244.220.150

**Comment by feroxib** [comment]
I recommend you removing that comment
since said ip is a digit ocean ip and probably your vpn
