### ISSUE TITLE
propose sample paths to user when creating new library

### ISSUE THREAD

**Issue by feroxib** [manyfold3d/manyfold#2311]
Would be nice to have if some directory paths could be "premade"/ indexed.
Consider the security aspects of that separately.

docker volume or direct path on disks could be displayed in a sort of dropdown menu in section: 
Library -> Path 

maybe the /libraries dir in docker could be used for that constructing a /libraries/${username_randomPostfix}/my_base_dir/new_library
where my_base_dir and other directories could be indexed on a per user level.

this would allow users to freely nest their directories.

**Comment by Floppy** [comment]
This is getting a rewrite soon as part of #1670 and #1385 , and is also related to #2242. I hope I can make this much friendlier.
