### ISSUE TITLE
add password strength meter for direct user feedback

### ISSUE THREAD

**Issue by feroxib** [manyfold3d/manyfold#2316]
in regard to #2277 and #2238

a complexity estimation of the user password on account creation and password change would be a nice addon. Considering that manyfold will be an exposed webpage.

found this here:
https://github.com/dropbox/zxcvbn

apparently works different and tries to consider a more realistic model for attacks.

maybe give this article a read too. since it explains it decently:
https://dropbox.tech/security/zxcvbn-realistic-password-strength-estimation

what's Todo?

- check if desired 
- might be worth scouting for an open source solution 
- integrate

**Comment by feroxib** [comment]
oh I just found #2203

since it's already planned to be integrated I'm going to close this

**Comment by Floppy** [comment]
Hehe yep, it's on the list :)
