### ISSUE TITLE
Improvement: Add .stl to Dropdown for file upload

### ISSUE THREAD

**Issue by mtbrgeek** [manyfold3d/manyfold#2324]
**Is your feature request related to a problem? Please describe.**
When the dialog box pops up to select files to upload, it currently has the zip/7z files as one dropdown option and *.*

**Describe the solution you'd like**
It would be useful to add a second item to that dropdown that includes .stl and the other file formats this supports

**Comment by Floppy** [comment]
This is in v0.70.0, coming soon 👍🏻

**Comment by mtbrgeek** [comment]
Good Deal!
