### ISSUE TITLE
.svg Logo to add to dashboard-icons

### ISSUE THREAD

**Issue by PyrokineticDarkElf** [manyfold3d/manyfold#2328]
Would you be able to provide a .svg or other vector file of the Manyfold logo? I would like to see it in [dashboard-icons](https://github.com/walkxcode/dashboard-icons)

**Comment by Floppy** [comment]
This would be awesome. I have a WIP one I'm trying to create at the moment, but it's a bit awkward because the original logo is (I'm a bit ashamed to say) AI generated, and I've got to try to (roughly) recreate it. And I'm terrible at graphic design. Good to know there's a reason for me to do so though.

**Comment by PyrokineticDarkElf** [comment]
Ahhh, I hadn't looked at it up close, but I can see that now hahah Could be hard to recreate as a vector...
I'm not bad on Illustrator, I could take a look for you when I get some time but I can't promise it would be as detailed as the original.

That said, if you're already close to having it finished, I'll leave it with you 😅 Let me know?

**Comment by Floppy** [comment]
An SVG definitely won't be as detailed, I'm just hoping to capture the essence of it in something cleaner really. I was thinking of putting the job out on fiverr, but I'll post my WIP here later on in case you do fancy taking a look!

**Comment by Floppy** [comment]
Coming back to look at these two side by side, I really think this is almost there. I think maybe I just need to tweak the opacity on some of the purples to get some variety back in there.

**Comment by Floppy** [comment]
I think that might do it, actually!

![background](https://github.com/user-attachments/assets/0a332b34-dfc6-4365-9f2c-846a68983531)

**Comment by Floppy** [comment]
So, https://manyfold.app/images/background.svg is now in use on the website. I've tried to make a clipped version at https://manyfold.app/images/roundel.svg for use as an icon, but for some reason although it looks OK in Inkscape, it doesn't appear at all in my browser. So that's odd.

**Comment by PyrokineticDarkElf** [comment]
I downloaded the files and tried them in Illustrator but they seem to be missing a lot of filters/blurs. I think some Inkscape features don't transfer over that well to Illustrator (and I assume maybe web too). When you exported, did you use 'Plain' SVG or 'Inkscape' SVG?

I've taken all the paths and applied similar blurs using Illustrator to produce these:
![edited-1](https://github.com/user-attachments/assets/185c1386-eece-4bde-8a35-3601cb60d9d6)
![edited-2](https://github.com/user-attachments/assets/b6343e0e-319d-4765-b74d-3c874524bbe3)

Let me know if they work any differently?

**Comment by Floppy** [comment]
Hm, saved as plain SVG and still no good.

**Comment by Floppy** [comment]
Yours look good, but they're absolutely massive (>1M each), I guess because they seem to have raster layers in them, rather than being pure vector SVG?

**Comment by PyrokineticDarkElf** [comment]
Ahhh. ngl, I didn't check the file size... I think it's also rasterised some of the paths. Now I've reopened the file I can't edit the middle...

Lemme give it another go

**Comment by PyrokineticDarkElf** [comment]
These should work. They use SVG filters - not rastered

It looks like Illustrator can create SVG filters for Gaussian Blur, but for whatever reason, whenever you open the file in Illustrator, it just ignores them. Inkscape can still see them tho.

You may want to modify the circular one a little since it's still using the original artboard size rather than being 1:1

![logo-main-mod](https://github.com/user-attachments/assets/31801ecb-1528-4a81-a1bf-24f175fbb665)
![logo-main-mod-c](https://github.com/user-attachments/assets/18c94482-b06e-4bc4-8b9b-b2cdab1a4d52)

FYI, I'm not convinced there was actually anything wrong with your original files, I've had another go at clipping the original icon you provided, let me know if this works when uploaded. I think the issue was, the circle used for clipping had a stroke and no fill? I think I prefer yours:

![logo-clipped](https://github.com/user-attachments/assets/afc795b7-48a4-42ca-bfa5-7da24ff90448)

**Comment by Floppy** [comment]
That did it, perfect! Can you tell I have no idea what I'm doing? 😁 

That rounded SVG is now at https://manyfold.app/images/roundel.svg, so we can get it submitted into dashboard-icons :)

**Comment by Floppy** [comment]
PR opened at https://github.com/walkxcode/dashboard-icons/pull/753 ❤️

**Comment by Floppy** [comment]
It just got merged :)

**Comment by Floppy** [comment]
And it works straight away in Homarr! 

<img width="164" alt="Screenshot 2024-07-20 at 21 51 26" src="https://github.com/user-attachments/assets/01bbebe8-09ac-49ad-b919-2e78a0e8f734">

**Comment by PyrokineticDarkElf** [comment]
Working on my Homepage install too :D

![image](https://github.com/user-attachments/assets/5353ef4b-9a03-4df5-8a3b-99d88ed62ff4)

**Comment by Floppy** [comment]
Amazing. What a time to be alive 😍
