### ISSUE TITLE
storage :library_1 isn't registered on Shrine

### ISSUE THREAD

**Issue by totalanni** [manyfold3d/manyfold#2330]
**Describe the bug**
When scanning for changes and trying to get an image of the model, I am presented with the following error "storage :library_1 isn't registered on Shrine"

**To Reproduce**
1. Upload Model or scan for changes
2. See error

**Expected behavior**
Scan to happen and 3d display of model to appear

**Screenshots**
https://i.ibb.co/3pwpkXK/image.png

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser Chrome

**Comment by totalanni** [comment]
22:58:56 default_worker.1     | 2024-06-30T02:58:56.211Z pid=34 tid=12ga WARN: {"context":"Job raised exception","job":{"retry":10,"queue":"scan","wrapped":"ModelScanJob","args":[{"job_class":"ModelScanJob","job_id":"32f968bc-2c56-4574-8135-5cc2b271848a","provider_job_id":null,"queue_name":"scan","priority":null,"arguments":[1,{"include_all_subfolders":false,"_aj_ruby2_keywords":["include_all_subfolders"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2024-06-30T00:27:00.644055036Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"5a363d50b12d41ce1072d62b","created_at":1719707220.6441026,"enqueued_at":1719716336.1862683,"error_message":"storage :library_1 isn't registered on Shrine","error_class":"Shrine::Error","failed_at":1719716336.210461,"retry_count":8,"retried_at":1719712205.2808805,"processor":"f501c5dd34e9:34"}}

I think the following error showed up in a "Timed Libary Scan"?

**Comment by Floppy** [comment]
This is happening because the library has been created but the workers don't know about it, as they're in another process. I'll get a fix out soon, but in the meantime restarting the container should make it work.
