### ISSUE TITLE
Couldn't find Library 

### ISSUE THREAD

**Issue by juanjomurga** [manyfold3d/manyfold#2331]
**Describe the bug**
The application indicates that the library cannot be found with id=3. Previously the application worked correctly and all models were visible. Currently, all references are broken

07:13:10 default_worker.1     | 2024-07-01T07:13:10.844Z pid=103 tid=46dn class=Analysis::AnalyseModelFileJob jid=68482409acbcd9102ae24fe6 elapsed=0.02 INFO: fail
07:13:10 default_worker.1     | 2024-07-01T07:13:10.844Z pid=103 tid=46dn WARN: {"context":"Job raised exception","job":{"retry":10,"queue":"analysis","wrapped":"Analysis::AnalyseModelFileJob","args":[{"job_class":"Analysis::AnalyseModelFileJob","job_id":"67a1f54f-bb00-402b-9de5-f615f7a4a147","provider_job_id":null,"queue_name":"analysis","priority":null,"arguments":[2350],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2024-07-01T06:54:02.386767225Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"68482409acbcd9102ae24fe6","created_at":1719816842.3868642,"enqueued_at":1719817990.823982,"error_message":"Couldn't find Library with 'id'=3","error_class":"ActiveRecord::RecordNotFound","failed_at":1719817990.842695,"retry_count":5,"retried_at":1719817331.8000984,"processor":"manyfold:103"}}
07:13:10 default_worker.1     | 2024-07-01T07:13:10.845Z pid=103 tid=46dn WARN: ActiveRecord::RecordNotFound: Couldn't find Library with 'id'=3
07:13:10 default_worker.1     | 2024-07-01T07:13:10.847Z pid=103 tid=46dn WARN: app/uploaders/library_uploader.rb:6:in `block in <class:LibraryUploader>'
07:13:10 default_worker.1     | app/jobs/analysis/analyse_model_file_job.rb:18:in `perform'

**To Reproduce**
This error occurs since the application was updated to its latest version (June 29)

**Screenshots**
![image](https://github.com/manyfold3d/manyfold/assets/174307823/4f247685-4d61-43bd-b0a7-e37865e70778)

**Docker
The application is run in docker. The pc is:
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Linux 6.1.0-0.deb11.21-amd64

**Comment by Floppy** [comment]
Have you set PUID and PGID in your Docker config? Does that uid/gid have permissions to the library folder? The whole thing disappearing feels like it just can't see it any more...

**Comment by juanjomurga** [comment]
Yes, the folders are assigned to the admin user and the users group. The admin user ID setting is 998 and 100.
Permissions for folders and other files are correct.

![image](https://github.com/manyfold3d/manyfold/assets/174307823/e57ac7ac-51b6-42a0-abc4-5bf989ef82ea)

![image](https://github.com/manyfold3d/manyfold/assets/174307823/b275274f-4604-447c-a36a-af97c15c428f)

**Comment by Floppy** [comment]
If you updated on June 29, I guess you're running v0.70.0 (shown in the footer). Had you run v0.69.0 successfully before this, or did you upgrade from an older version?

**Comment by juanjomurga** [comment]
v0.69.0 worked correctly and I applied the necessary changes to the permissions.
If there are no additional changes in the database, I can even export the database and perform a clean installation to v0.70.1.
I don’t know how feasible it is to do this or if I’ll find more trouble. There are many models that I have added to the database, but if this can help you verify some additional behavior...

Actually, it’s a strange behavior. I’ll keep checking the log of the different components to see if I find any additional errors.

What I can tell you is this:

- Add a model correctly (unzip the zip file in the corresponding folder)
- Creates the register in the database
- Displays the correct number of files on the model page, but they are not displayed
 
![image](https://github.com/manyfold3d/manyfold/assets/174307823/4cffb859-c8b0-44ce-a963-b51bd1372571)

This seems to be a problem with user permissions. I’ll try (even if a security warning pops out) to put the root user as the owner. Maybe I can see some additional behavior

**Comment by Floppy** [comment]
Very odd that v0.69.0 worked and v0.70.0 doesn't... I'd expect both to act the same way. Yeah, give it a try as root.

It's safe to downgrade from v0.70.0 to v0.69.0, nothing will be lost, so you could also try that.

**Comment by Floppy** [comment]
oh, wait, sorry, I've misread something. I'm debugging two different permission problems at the same time and got confused.

It's not managing to load the information from the database itself, not the filesystem. Do the sidekiq workers have correct access to the same database as the main app?

**Comment by Floppy** [comment]
And can you see any errors in the log in advanced admin, or `docker logs`? Perhaps try watching docker log, then going to a model page, and seeing what error pops up.

**Comment by juanjomurga** [comment]
I couldn’t find any additional errors. What is true is that it seems that the path is something strange or that seems to me, although it may be my mistake.

![image](https://github.com/manyfold3d/manyfold/assets/174307823/daf0583f-acfa-4b3b-84d0-2079ce84c10c)

sidekiq shows the same error as manyfold

![image](https://github.com/manyfold3d/manyfold/assets/174307823/f54f7c02-4b7a-4e18-8561-d3653f39962d)

REDIS show the following log:
![image](https://github.com/manyfold3d/manyfold/assets/174307823/f46f89e0-3c55-4428-8d39-0811ca64a6b4)

I don’t see any problems with cross-platform connections

**Comment by Floppy** [comment]
the log above says `Couldn't find Library with 'id'=3`, but the URL you have there is `/libraries/35`. That seems very odd...

**Comment by Floppy** [comment]
If you click on the sidekiq button just above the activity log, you can see the queues. Are there a lot of old jobs queued up? Could there be old jobs from a deleted library that actually just need deleting?

**Comment by juanjomurga** [comment]
No jobs in queue.
![image](https://github.com/manyfold3d/manyfold/assets/174307823/d948f1cb-eafd-4ce2-a32d-2edb06fda7d0)

I didn’t create any additional library. I created a single library that I’ve kept all this time.
What is the possibility of trying to update the libreries table to update the id?

**Comment by Floppy** [comment]
A single library? Wow, then I'm really confused. 

How on earth is it id 35? And why is it trying to run jobs on id 3? All those IDs should be coming from the database, there's nothing else... so even changing the ID wouldn't help because .... where is it even getting those? Hmmmm. I'll keep thinking.

**Comment by lukasbasedow** [comment]
I am experiencing the same issue. Only one of my libraries doesn't load correctly anymore (same error as already shown), and the database is spamming the error "Couldn't find Library with 'id'=1." The library ID is 11.

**Comment by Floppy** [comment]
... so it's like the library ID is getting chopped off at the first digit? That's *bizarre*. OK, I'm on it.

**Comment by Floppy** [comment]
Wow. I've found it. The storage engine being fetched is wrong if the ID has multiple digits. Each attachment has a storage key in it, for instance `:library_11` for the library with ID 11. BUT, when I fetch that storage, I'm getting back storage ID 1. So it is *literally* getting the last digit chopped off. I'll get this fixed and get a bugfix release out. Thank you both for the information @juanjomurga @lukasbasedow, I would never have thought of that being a problem!

**Comment by lukasbasedow** [comment]
Thank you for the super fast fix. Happy that the comment helped. After updating, the Libary is working again <3

**Comment by Floppy** [comment]
FIxed and released in v0.70.3 which is now ready to pull.

**Comment by Floppy** [comment]
@lukasbasedow you're welcome! Love finding things like that 😄 

Great to know it's working ❤️

**Comment by juanjomurga** [comment]
I was afraid of having to do some kind of trick to not lose all the logs (over 500) and install the application from 0.

Thank you very much for the solution. Perhaps, as an idea, it would be nice to be able to make a button that includes an export/import of what we have in the database, in case we migrate or find problems...

Again, thank you for your amazing work and quick solution
