### ISSUE TITLE
Error in Advanced Admin Library view

### ISSUE THREAD

**Issue by BRAYDIN72** [manyfold3d/manyfold#2363]
**Describe the bug**
Going into advanced administration and then libraries generates an error 

I, [2024-07-07T13:32:15.931378 #131]  INFO -- : [1c4ffc87-7d7c-46aa-9de9-5a1d4caae214] {"method":"GET","path":"/admin/libraries","format":"html","controller":"Admin::LibrariesController","action":"index","status":500,"allocations":94114,"duration":75.37,"view":0.0,"db":4.01,"@timestamp":"2024-07-07T18:32:15.931Z","@version":"1","message":"[500] GET /admin/libraries (Admin::LibrariesController#index)"}
F, [2024-07-07T13:32:15.933980 #131] FATAL -- : [1c4ffc87-7d7c-46aa-9de9-5a1d4caae214]   

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Advanced Administration'
3. Click on Libraries

**Expected behavior**
Hopefully find a place to rename or change the folder name of a library

**Screenshots**

![Screenshot 2024-07-07 134342](https://github.com/manyfold3d/manyfold/assets/42328309/0de0123f-d659-48f9-a27c-61cef97c1114)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 126.0.6478.127
Server: Docker (UnRaid) 
Manyfold Version v0.71.0

**Comment by Floppy** [comment]
Thanks! I'll check it out.
