### ISSUE TITLE
Tagging during upload

### ISSUE THREAD

**Issue by s5n1el** [manyfold3d/manyfold#2382]
**Is your feature request related to a problem? Please describe.**
Group tagging on bulk upload 

**Describe the solution you'd like**
It would be immensely helpful to have a field where we could pre-specify a tag or set of tags that get added to the models uploaded

**Comment by Floppy** [comment]
Ideally, this should use the same form as bulk editing, meaning that you could set any of the same fields at upload time. Creator, collection, tags, license, permissions (once #2618 is done) etc.
