### ISSUE TITLE
Purge deletes non-empty folder

### ISSUE THREAD

**Issue by squk** [manyfold3d/manyfold#2416]
**Describe the bug**
Purge deletes non-empty folder

**To Reproduce**
1. Create a folder
2. Add a STL to the folder
3. Scan
4. Remove STL from the folder
5. Scan
6. Purging folder from "problems" deletes the folder and all of it's subdirectories, which may contain other models!

**Expected behavior**
Purge the database entry for the folder, not its contents.

**Comment by Floppy** [comment]
Oof, it shouldn't be doing that if there are other models in there! Thanks for flagging it up, I'll check.

**Comment by Floppy** [comment]
Wait, I misunderstood. Purging a missing *file* removes the whole *folder* and subdirectories??

**Comment by Floppy** [comment]
I'm afraid I can't replicate this locally; can you provide any more details? Like, the exact contents of the model before purging, a screenshot of the button, etc?

**Comment by squk** [comment]
Here's a better description of the issue:

```
Armor
├── Shoes.stl
├── Shoulders
│   ├── 1.stl
│   ├── 2.stl
│   ├── 3.stl
├── Chest
│   ├── 1.stl
│   ├── 2.stl
│   ├── 3.stl
```

Delete or move `Shoes.stl`:

```
Armor
├── Shoulders
│   ├── 1.stl
│   ├── 2.stl
│   ├── 3.stl
├── Chest
│   ├── 1.stl
│   ├── 2.stl
│   ├── 3.stl
├── Feet
│   ├── Shoes.stl
```
The "Armor" model that contained `Shoes.stl` now appears as empty in issues and is given the option to "Purge". If you do purge, `Shoulders`, `Chest`, and `Feet` are deleted and there's no other way to remove the `Armor` model.

**Comment by Floppy** [comment]
Ah fantastic, I'll give that a try in order to reproduce it.

**Comment by Floppy** [comment]
I've got this replicated now, should be fixed soon.
