### ISSUE TITLE
Canceled Upload Archive Duplication

### ISSUE THREAD

**Issue by oathboundFamiliar** [manyfold3d/manyfold#2455]
**Describe the bug**
Canceling an upload, and then proceeding to upload the archive again without refreshing the page will result in model creation using the original archive. I encountered this when modifying archives for optimal storage on our filesystem.

**To Reproduce**
1. Upload an archive containing models
2. Cancel the upload
3. Upload an archive of the same name (e.g. modify the original archive and upload it again) without refreshing the page
4. Create a new model using this upload

**Expected behavior**
Canceling the upload should clear the cached version and/or uploading an archive of the same name should overwrite it

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04
 - Browser: Firefox 128.0.2

**Comment by Floppy** [comment]
Ooh, that's an interesting one. I guess it's reusing the cache key somehow.

**Comment by Floppy** [comment]
I've seen this locally now, I think it's related to #2594 as well.

**Comment by Floppy** [comment]
OK, the problem here is that Uppy (the upload UI) isn't clearing successful uploads from the submitted form, probably because of something I've done wrong? So, a completed but unused upload is still getting sent when the form is submitted.
