### ISSUE TITLE
New Creator/Collection button on item edit doesn't redirect back to item after creation

### ISSUE THREAD

**Issue by AevumDecessus** [manyfold3d/manyfold#2461]
**Describe the bug**
New Creator/Collection buttons on item edit pages don't redirect back to the item edit page after creation

**To Reproduce**
1. Go to edit and model
2. Click on "New Creator" or "New Collection"
3. Fill out new creator/colllection information
4. Click "Save"

**Expected behavior**
I expect to return to the item edit page that I had open, with the new creator pre-selected

**Actual Behavior**
I am redirected to the creators/collections page and have to go back to find the model I was editing in the first place

**Comment by Floppy** [comment]
This is a very good point. Thanks!
