### ISSUE TITLE
Merging causes files to be deleted

### ISSUE THREAD

**Issue by ChronoStriker1** [manyfold3d/manyfold#2496]
**Describe the bug**
When merging a model into another the files be merged will be deleted.

**To Reproduce**
1. Have nested folders
2. Import a new model or scan for a model you manually placed in the file system
3. Click on "New model"
4. Click on Merge button on a model
5. It will look like it merged in the interface but you will now have a file missing warning, files will be missing from the file system.

**Expected behavior**
The new model will merge into the existing suggested model.

**Screenshots**
I would but I would loose more files...

**Desktop (please complete the following information):**
 - OS: Unraid 7.0.0-beta.2 - using docker compose
 - Browser Any
 - Version 0.74.2 (975441b7)

**Comment by Floppy** [comment]
That's worrying... I'll look into it!

**Comment by Floppy** [comment]
Try as I might, I've not been able to replicate this on either dev or production systems, so I'm going to close it; if you can provide any more detail on how it happened, such as the particular folder structure you mean by "have nested folders", feel free to reopen it, but for now I don't really have any way forward 🫤

**Comment by Floppy** [comment]
In this situation:

1) A new model gets created for the subfolder, as it has new files in it!
2) That new model adds all the files in the folder, some of which may be present in a parent model.
3) When it's merged, the duplicated files get moved over the top of themselves, which ends up with them being deleted somehow.

We could resolve this by either checking for existing models with the same path in the parent model before creating them, or by automatically including files in subfolders into the parent model on rescan (assuming the subfolder doesn't have a model already).
