### ISSUE TITLE
Change a example docker compose  value

### ISSUE THREAD

**Issue by Mallo321123** [manyfold3d/manyfold#2510]
add the "restart: unless-stopped" value in the example docker compose.

Just a Reminder for @Floppy

**Comment by Sakh1l** [comment]
can i take this?

**Comment by Floppy** [comment]
Sure thing! The repo at https://github.com/manyfold3d/website is probably the best place for it, along with docker-compose.example.yml in this repo if you want.

**Comment by Mallo321123** [comment]
New update here: https://github.com/manyfold3d/website/pull/63
