### ISSUE TITLE
S3 storage problems (Several)

### ISSUE THREAD

**Issue by aneurinprice** [manyfold3d/manyfold#2518]
**Describe the bug**
Multiple problems attempting to use the S3 storage type.

I am running Minio (self hosted s3) with an SSL certificate which is valid (although not signed by known upstream).

With this in mind, I have mounted my CA into the container:

```
handles:~ aneurinprice$ kubectl exec -it -n apps-manyfold manyfold-0 -- /bin/sh
/usr/src/app # apk add curl
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/6) Installing brotli-libs (1.0.9-r14)
(2/6) Installing libunistring (1.1-r1)
(3/6) Installing libidn2 (2.3.4-r1)
(4/6) Installing nghttp2-libs (1.57.0-r0)
(5/6) Installing libcurl (8.9.0-r0)
(6/6) Installing curl (8.9.0-r0)
Executing busybox-1.36.1-r5.trigger
OK: 41 MiB in 57 packages
/usr/src/app # curl https://barnyard.virtual.nyeprice.local:9000
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><Region>eu-west-1</Region><RequestId>17EB4DE790AE4ACE</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>/usr/src/app # 
```

As you can see, the container accepts the certificate.

Now for the problems:

After adding the storage backend as S3, I try to upload to Manyfold.

Sidekiq:

```
Shrine::FileNotFound: file "90fd6f974cbf4f0f069147ff022e29f3.zip" not found on storage

Processor: manyfold-0:126
```

This is as much of an error message as I can get. Unfortunately there is not an error that I can see on the actual upload. The bucket stays empty, so the upload never completes and just sits there with:

```
 Failed to upload Sweater meme Rosalina.zip Upload error
 ```
 
 Using: `Version: [0.75.1 (f0a19913)]`
 
 If you need anything else please do let me know :)

**Comment by Floppy** [comment]
S3 isn't being used for the cache, that will still be local storage... can you tell if that file appears in /tmp or similar on the docker host?

**Comment by Floppy** [comment]
Uploaded files should appear in /usr/src/app/tmp/cache before they're processed. See if anything ends up in there?

**Comment by Floppy** [comment]
You can mount any folder you like at that location, if that helps. I'm hoping to allow proper setting of cache location in future, as it should be properly controllable.

**Comment by aneurinprice** [comment]
> Uploaded files should appear in /usr/src/app/tmp/cache before they're processed. See if anything ends up in there?

Files do not make it into the cache folder

**Comment by aneurinprice** [comment]
I figured it out. It was bnot a problem with the app, although logging could be inmproved.

I had not allowed a larger upload size on my ingress resource, that's why the upload failed.

I will close this issue, but perhaps a more useful error message is something we can consider?

**Comment by Floppy** [comment]
Ah, so in a separate setting to the app's own setting? That would do it. 

Definitely we could try to improve the error reporting in that situation, yes.

**Comment by aneurinprice** [comment]
> Ah, so in a separate setting to the app's own setting? That would do it.

Exactly. If you are unfamiliar, a kubernetes ingress controller is essentially just a reverse proxy. 
The upload file limit in the app itself works, but it also needs setting on the reverse proxy.
