### ISSUE TITLE
Error Message when opening http://localhost:8040

### ISSUE THREAD

**Issue by stgordon2** [manyfold3d/manyfold#2521]
I received the following error after creating a new solo install of manifold in portainer. Error only occurs after uploading the first model. 

![Manyfold_Error](https://github.com/user-attachments/assets/6b6cf0bb-7bd4-4f89-afbf-9309b6da1fd4)

**Comment by Floppy** [comment]
Can you see any error messages in /usr/src/app/log/production.log inside the container?

**Comment by Floppy** [comment]
Ah, looks like a permission problem; does the user Manyfold is running as have access to the folder you've mounted at /libraries?

**Comment by Floppy** [comment]
I've got a feature issue open at #2505 that should flag this up properly so it can be avoided in future. Glad you got it solved!
