### ISSUE TITLE
Multi-Zip upload creates duplicates

### ISSUE THREAD

**Issue by aneurinprice** [manyfold3d/manyfold#2525]
When uploading 4+ zip files, the upload completes successfully, but we end up with multiple (incorrect) models (Please see screenshots)

**To Reproduce**
1. Go to `Upload`
2. Upload 4 or more .zip files
3. Complete Upload
4. Return to main menu

**Expected behavior**
We should not end up with multiple models for same zip file.

**Screenshots**
![image](https://github.com/user-attachments/assets/44dd935b-95aa-4149-81cc-af9df945c974)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 128.0.2

**Additional context**

`Version: 0.75.1`
database adapter postgresql
storage driver for library (hostpath)

**Comment by Floppy** [comment]
This could be the same as #2472

**Comment by aneurinprice** [comment]
Looks like it

**Comment by Floppy** [comment]
If you look in the "failures" tab in the sidekiq UI, do you see anything like this, with the conflicting chdir?

<img width="993" alt="Screenshot 2024-08-19 at 14 57 47" src="https://github.com/user-attachments/assets/33443b4f-51d7-4a35-be9f-b701e373b55a">

**Comment by Floppy** [comment]
Apparently chdir isn't thread-safe, so we can't use it. That would cause failures, which then causes duplicate folders to be created.

**Comment by aneurinprice** [comment]
@Floppy 

![image](https://github.com/user-attachments/assets/eadb3064-bc55-4650-b718-c2538e3aa4a7)

Conflicting chdir seems to be the culprit!

**Comment by Floppy** [comment]
OK, that's a common cause of failures then, which in turn causes the repeated models. #2472 has a different cause (permissions) but the same duplication of models on retry.

**Comment by Floppy** [comment]
#2529 improves the error handling to fix the multiple models, and #2530 is on the list for the underlying issue that causes the failures in the first place.
