### ISSUE TITLE
Image preview breaking if there are too many images in same model

### ISSUE THREAD

**Issue by DrazorV** [manyfold3d/manyfold#2546]
This is a model with 90 images in it.
![image](https://github.com/user-attachments/assets/5a595c63-a199-4841-afe5-8b6ed052b97f)

As you can see the numbers (carousel) on the bottom is broken
![image](https://github.com/user-attachments/assets/fe6f87fa-d82f-4ec1-9943-2d00ce303b97)

**Comment by Floppy** [comment]
lol, that's a lot of images. You bring me the best bugs with huge libraries :D
