### ISSUE TITLE
Invalid data caused by unsetting "presupported"

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#2566]
If I file is marked as a presupported version of another, but is then edited to remove the presupported flag, the other model can no longer be saved, as its presupported version is no longer presupported.

This can cause data migration problems, as well as one-off incorrect data.

**Comment by aetherith** [comment]
Hi, so I'm facing this exact issue in an upgrade from v0.69.0 to v0.70.3. Is there a query or something I can run to find which file is the problem so I can correct it?

**Comment by Floppy** [comment]
Gah, sorry about that. I've just added something to the "advanced tasks" page to print out any invalid files, which should then let you go and fix them manually: https://manyfold.app/sysadmin/advanced_tasks.html#debugging-invalid-files
