### ISSUE TITLE
Bulk Edit page pagination and filtering

### ISSUE THREAD

**Issue by DrazorV** [manyfold3d/manyfold#2585]
Having this huge library makes bulk edit page almost unusable, it takes more than 1 minute to load the page and it loads every model in my library, resulting in a huge scrolling screen without any way of filtering.

![image](https://github.com/user-attachments/assets/82d268d0-5178-4dd6-9bcb-e7a3ff707a40)

**Comment by DrazorV** [comment]
On previous versions (before we removed the synology generated thumbnails) this page didn't load.
I was always getting time out error after some minutes.

**Comment by Floppy** [comment]
Is this the models bulk edit page, rather than files? If so, it should respond to currently-applied filters correctly. I admit it doesn't have pagination though :)

**Comment by DrazorV** [comment]
It is indeed the models bulk edit page. I didn't know that it uses the applied filters, it makes sense now that you say it.. A page size (maybe same as the one set on the settings) and a pagination will help a lot with big libraries.

**Comment by Floppy** [comment]
And it should make clear that the filters have been applied!
