### ISSUE TITLE
Migration fails on update (and is stuck in loop)

### ISSUE THREAD

**Issue by lambi21** [manyfold3d/manyfold#2643]
**Describe the bug**
Updating to the latest manyfold-solo instance (edge), starting the docker container is not successful. Log produces "Could not find table 'caber_relations'" error, and then the server retries to start up endlessly.

**To Reproduce**
Update an older installation (I think my previous one was 0.74 or 0.73) and update to latest edge version

**Expected behavior**
Update and start as usual

**Screenshots**
see log in attachment
[log.txt](https://github.com/user-attachments/files/16919906/log.txt)

**Desktop (please complete the following information):**
Docker image running on unraid server

**Comment by Floppy** [comment]
I'm having some problems myself with edge at the moment; if you stick to `latest`, does that work OK?

**Comment by Floppy** [comment]
Hm, actually, it probably won't help, I can see how this might happen. If you upgrade to 0.76.0 first, then to 0.77.3, it will probably be OK. I'll see if I can fix it.

**Comment by lambi21** [comment]
> Hm, actually, it probably won't help, I can see how this might happen. If you upgrade to 0.76.0 first, then to 0.77.3, it will probably be OK. I'll see if I can fix it.

That worked, thanks!

**Comment by Floppy** [comment]
Great - that also means I know how I need to fix it!
