### ISSUE TITLE
Uploaded files remain in /tmp/cache until container is restarted

### ISSUE THREAD

**Issue by EcceGratum** [manyfold3d/manyfold#2644]
**Describe the bug**
I uploaded large amount of zip files (80Gb) and noticed at least some of them (if not all) stayed in /tmp/cache until the container is restarted. I had no more free space on system partition and any further upload would fail.

**To Reproduce**
1. upload zip files
2.  Check the tmp/cache directory size of the container

**Expected behavior**
Files should be removed from /tmp/cache once Manyfold unzipped and moved them to the destination folder

**Desktop (please complete the following information):**
 - OS: Kubuntu 24.04
 - Browser: Chrome
 - Version: 128.0.6613.120

**Additional context**
Maybe linked to https://github.com/manyfold3d/manyfold/issues/2136

**Comment by Floppy** [comment]
Thanks! I will add something to sweep them up.

**Comment by Floppy** [comment]
Could also be linked to #2455
