### ISSUE TITLE
Ability to add a note to models (To describe print options, etc...)

### ISSUE THREAD

**Issue by EcceGratum** [manyfold3d/manyfold#2671]
**Is your feature request related to a problem? Please describe.**
Currently, we can't add notes to models. The same model may need specific or different print options for FDM with different nozzles, Resin printer, etc... 

**Describe the solution you'd like**
I think the ability to add a note in the model details when we open a model could be a solution. Perhaps saved as a text file just in case it's not lost when the DB is corrupted.

**Describe alternatives you've considered**
I explored the app but could not find any other way to add notes to a model, an alternative would be to have a text file with it sent during the upload of the model or inside the zip. Not sure how to visualize the text file inside Manyfold but probably doable. At least even if the database crashes, the note is in the text file and not lost.

**Comment by EcceGratum** [comment]
My bad, i found it in the edit section of the model.

**Comment by Floppy** [comment]
No worries! Shows I need to make it a bit more obvious :)
