### ISSUE TITLE
Visiting a non-public model page without being logged in just displays a blank 403 page

### ISSUE THREAD

**Issue by AevumDecessus** [manyfold3d/manyfold#2695]
**Describe the bug**
Visit a model page that isn't public without being logged in, and you get a completely blank 403 error page

**To Reproduce**
1. Log out of manyfold
2. Visit the URL of any model that isn't public
3. Get a completely empty page with an HTTP 403 return code

**Expected behavior**
I expect to see an error page with an option to log in to view the model

**Screenshots**
![image](https://github.com/user-attachments/assets/5da1e910-2f77-4c58-a1a5-92e6d30d7050)

**Comment by Floppy** [comment]
Thanks for filing this, I notice it every now and again while doing something else, and keep meaning to fix it.
