### ISSUE TITLE
Multiple tags with same number applied in inconsistent order when organizing

### ISSUE THREAD

**Issue by AevumDecessus** [manyfold3d/manyfold#2696]
**Describe the bug**

**To Reproduce**
1. Tag several models with the same tags the same number of times
2. Click on 'Organize'
3. Observer the inconsistent folder structure, and that some files consistently show the "Needs Organizing" flag

**Expected behavior**
If 2 tags have the same priority (applied to the same number of models), we should probably just stick those tags in alphabetical order so the folder structure is expected and consistent

**Screenshots**
Models with 2 tags applied to the same number of models `2x stack` and `mp41` are both applied to only these 9 models
![image](https://github.com/user-attachments/assets/64d0b426-8552-47ff-8d00-cb87e2deb7e8)

Organize dialog on one model, showing it prioritizing `mp41` over `2x stack` tags for folder structure
![image](https://github.com/user-attachments/assets/e52284aa-bc84-416f-b07c-d3dbffc9ad85)

Interestingly, manyfold seems to consistently pick the `mp41` tag as priority in this case, but it doesn't actually move the files when you click organize if the `2x stack` tag was prioritized in the existing folder structure

**Additional context**
Manyfold seems to consistently prioritize the `mp41` tag in my case, even though it's later alphabetically, and has a higher ID, not sure how it's picking priority
![image](https://github.com/user-attachments/assets/acac8c76-33c2-4e6f-a159-45ef6048c712)

**Comment by Floppy** [comment]
Looks like somewhere down the stack I'm sorting them, but not consistently. Thanks for filing it!
