### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by kidbluei** [manyfold3d/manyfold#2713]
**Describe the bug**
When viewing lists of creators and objects, sorting lists capital letters first followed by lower case (e.g. ALPHA, CHARlie, Bravo, alpha2).

**To Reproduce**
1. Go to "Creator" Tab or "Models" tab.
2. Scroll down list until you find sorting is inconsistent.

**Expected behavior**
Records should be sorted regardless of case (e.g. ALPHA, alpha2, Bravo, CHARlie) I believe this was the case with previous versions (0.68.0).

**Screenshots**
1) List of creators restarting from Zororeo to basti30 and continuing with lowercase entries.
![sorting 1](https://github.com/user-attachments/assets/eadb4045-520a-4837-8659-51de22ab3aa2)

2) Same behavior when editing model details and selecting a creator.
![sorting 2](https://github.com/user-attachments/assets/54593db0-8a38-4534-8079-0564222b84a1)

3) Same behavior in list of models with square brackets and lower case "a" appearing at the end of the list (had to rename to cause this).
![sorting 3](https://github.com/user-attachments/assets/82117318-8cfe-411f-b071-9e80669980a0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 130.0

**Smartphone (please complete the following information):** 
n/a

**Additional context**
Currently using v0.78.1 solo deployment with Docker. Still seeing this in 0.79.0 that was just released.

**Comment by Floppy** [comment]
Good call! I don't think anything should have changed on that front, but you're right that it should be case insensitive!
