### ISSUE TITLE
Unable to edit/delete/use new libraries in 0.79

### ISSUE THREAD

**Issue by eloebl** [manyfold3d/manyfold#2732]
**Describe the bug**
When I create a brand new library If I go into the Advanced Admin interface, I can't delete them as it says the library isn't found (for the public id), but the library ID if I put that in the URL shows the details. I wondered if permissions, but if I go into a shell in the container(pod), I can create files and directories fine on the mount point

**To Reproduce**
1. Create new filesystem library
2. Go to the advanced library to edit or delete a library
3. Get an error that it can't find the library by the public ID
4. Edit the URL and change the public ID to the library ID integer, and it shows up, but can't edit/delete as it reverts to the Public ID due to pager source

**Expected behavior**
I should be able to edit/delete libraries from teh UI

**Screenshots**
![image](https://github.com/user-attachments/assets/64e4bcb6-17d8-4a79-a0e2-a267ba28a948)
![image](https://github.com/user-attachments/assets/9dc13a69-bc38-4cae-b515-aaebcf1ce425)
![image](https://github.com/user-attachments/assets/5b8479a9-cf9f-40f5-ab96-f4f8871af9d7)
![image](https://github.com/user-attachments/assets/0dabb219-9efa-4033-a7b0-3fa2d2b87548)
![image](https://github.com/user-attachments/assets/4849abc4-56c0-4b58-9c7f-b6463c0e62d4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser: Chome
 - Version Version 131.0.6724.0 (Official Build) dev (64-bit)

**Additional context**
* K3s kubernes 1.30
* NFS provisioner

**Comment by Floppy** [comment]
Does this affect library usage in the main app itself, or is it just in the admin interface?

**Comment by Floppy** [comment]
Ah, OK, I see this in my instance, the links in the admin interface don't work because it's using the public ID, and activeadmin doesn't understand what that is. Gotcha.

Would be good to know the library works OK for you in the normal app though...

**Comment by Floppy** [comment]
I suspect this will be the same for most stuff in the admin UI, in fact. Models, everything that now uses a public ID.

**Comment by Floppy** [comment]
https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#customizing-resource-retrieval has the details of what I need to do to get activeadmin working again.

**Comment by RawSmokeTerribilus** [comment]
This creates duplicates when adding libraries that are subfolders from other library, resulting on false positives. and if you are so smart as i am... you may destroy your models library. we absolutely need to be able to delete libraries. Is there any way to delete them manually?
