### ISSUE TITLE
Can't upload some files without an error

### ISSUE THREAD

**Issue by EmilyNerdGirl** [manyfold3d/manyfold#2734]
**Describe the bug**
Some of the stl, 3mf and zip files downloaded from 3rd parties may have a "+" in the name, and this will cause an upload error with no indication why it failed in the log
EDIT: Not an issue with name after all but something with the files and will attach

**To Reproduce**
1. Go to Upload
2. Place a file that's attached
3. Click upload
4. Get a Failed Upload for 3mf files,

**Examples**
* `set+of+5.3mf`  - Can't upload
*  Can upload but fails to render or `Skadis+18+pos+10mm+Paint+Pen.3mf`

**Expected behavior**
Should be able to handle special characters in the file name

**Screenshots**

![image](https://github.com/user-attachments/assets/14a3bf70-1f87-4555-8495-893881689ad8)
![image](https://github.com/user-attachments/assets/36d419f9-209d-4867-a972-b79a6637aa76)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser chrome
 - Version Version 131.0.6724.0 (Official Build) dev (64-bit)

[Failed3mf.zip](https://github.com/user-attachments/files/17085297/Failed3mf.zip)

**Comment by Floppy** [comment]
This looks to me like the same error as in #2640, so if you don't mind I'll close it as a duplicate. You mentioned STL though, do you have STL files that fail in the same way? Because as far as I know this would just be a 3MF problem...
