### ISSUE TITLE
User account in Collections/Creator creation log isn't always reported correctly in mutli-user instances:

### ISSUE THREAD

**Issue by SilverbackConnor** [manyfold3d/manyfold#2744]
**Describe the bug**
When a non "host"/admin/original(?) user creates a collection/creator, it's inaccurately reported as the original user (pictured):
![image](https://github.com/user-attachments/assets/a1b3c047-5617-485a-b07e-5ae30d612186)

**To Reproduce**
1.Create Multi User Instance (in my case, no sign-ups)
2. Add user account
3. Have added user account make a collection/creator

**Expected behavior**
It to report as the correct user making the creator/collection

**Screenshots**

**Comment by Floppy** [comment]
Thanks - I'll be looking at activity stuff again this week, so I'll fix this while I'm there.

**Comment by Floppy** [comment]
So, this is because we don't actually set a correct owner relationship for creators or collections! So it's nothing to do with the feed, it's deeper down than that. Thank you for pointing it out!
