### ISSUE TITLE
STL Models from Eldritch Foundry Failing to upload

### ISSUE THREAD

**Issue by EmilyNerdGirl** [manyfold3d/manyfold#2793]
**Describe the bug**
Trying to upload STLs from Eldritch Foundry models as Manyfold is the perfect tool for organization for models and minis, but getting an error on upload

**To Reproduce**
1. Download the STL model from Eldritch Foundry
2. Drag/drop the stil attached to bug report (or others tried)
3. When you click Create Models you get an upload error 

**Expected behavior**
Should be able to upload these files and possibly show an error why they failed to upload

**Screenshots**
Error occurs on hitting save so having been able to capture

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04

 - Browser: chrome
 - Version : Version 131.0.6724.0 (Official Build) dev (64-bit)

**Additional context**
I've attached the stl example that's failing, in this case it's just the base of the mini

[147037_268677_869591_base_mm.zip](https://github.com/user-attachments/files/17132835/147037_268677_869591_base_mm.zip)

**Comment by Eldritch-Foundry** [comment]
That's a zip file, mate? Did you try unzipping it first?

**Comment by Floppy** [comment]
@Eldritch-Foundry Manyfold should do the unzipping - I suspect that's where the problem lies :)

**Comment by Floppy** [comment]
@EmilyNerdGirl I uploaded it to my instance temporarily to check, but it seems to work fine there; can you see anything in the docker logs on your end that might point the way towards an error? Or, if you look at the activity list, is there an error there or in the Sidekiq UI?

**Comment by EmilyNerdGirl** [comment]
I figured out the issue for anyone that runs into this later. I was using nginx as a reverse proxy for k8s and it has a max data size set to 1mb.  Adding the following to the configmap for nginx resolved it:
```
data:
  client-max-body-size: 100m
```
