### ISSUE TITLE
Database migrations from 0.79.0 to 0.80.(0|1) fail

### ISSUE THREAD

**Issue by blacs30** [manyfold3d/manyfold#2815]
**Describe the bug**
The database migrations from version 0.79.0 to 0.80.1 / 0.80.0 fail.
I use postgresql version 11 as database.

**To Reproduce**
Have an older version (I started before 0.70 I believe and updated from time to time) and update it to 0.80.0

**Expected behavior**
Migrations should succeed.

**Additional context**
Logs excerpt from the errors:

```
/usr/src/app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'

Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "(" (PG::SyntaxError)
LINE 1: ...name_lower" character varying GENERATED ALWAYS AS (LOWER(nam...

and 

/usr/src/app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'

Caused by:
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "(" (ActiveRecord::StatementInvalid)
LINE 1: ...name_lower" character varying GENERATED ALWAYS AS (LOWER(nam...
                                                             ^

```

Postgresql logs:
```
2024-09-28 13:27:58.749 UTC [602760] ERROR:  syntax error at or near "(" at character 77
2024-09-28 13:27:58.749 UTC [602760] STATEMENT:  ALTER TABLE "models" ADD "name_lower" character varying GENERATED ALWAYS AS (LOWER(name)) STORED
```

Please let me know if you need other information

**Comment by Floppy** [comment]
Thanks! I'll have a look at it.

**Comment by Floppy** [comment]
Ah, this is because Postgres 11 doesn't support generated columns - they were introduced in 12. As Postgres 11 isn't one of their supported releases any more, I think it's sensible to say that it's not supported by Manyfold either, I'm afraid you'll need to upgrade to 12 or above, though note that 12 hits end-of-support-life this November too: https://www.postgresql.org/support/versioning/

**Comment by blacs30** [comment]
Thank you, that explains it. Thanks for the nice app.

**Comment by Floppy** [comment]
That's great news! And thanks for being OK with the answer, I was very uncomfortable saying I wasn't going to fix it!!
