### ISSUE TITLE
`undefined method `activities' for nil` During Database Migration

### ISSUE THREAD

**Issue by sdwilsh** [manyfold3d/manyfold#2816]
**Describe the bug**
`db:prepare:with_data` is failing in a loop for me on 0.80.1 with `undefined method `activities' for nil`.  I was previously running `0.79.0`, although I don't know if that was okay with migrations because I now realize I don't have a liveness check on the container.

**To Reproduce**
1. Start the application
2. See error in logs

**Additional context**
Manyfold version: 0.80.1
Full Logs: https://gist.github.com/sdwilsh/a741dc2b4aca6e936d487f0b406f8f50
Kubernetes StatefulSet definition: https://github.com/sdwilsh/ansible-playbooks/blob/main/kustomization/components/manyfold/statefulset.yml

**Comment by Floppy** [comment]
Thanks - this should be fixed in the next release; I'll try to get one out soon for you.
