### ISSUE TITLE
[Feature Request] Static thumbnails auto-generated for gallery views

### ISSUE THREAD

**Issue by profucius** [manyfold3d/manyfold#2827]
Currently, when viewing models in any gallery-type page (e.g. Models page), each object is always regenerated as a live model. For 3mf files that include images in the project file (I believe this is why), this can take multiple seconds each to load the render, and without caching, this happens every time a page is changed.

Example file. Try importing both files separately. The 3mf takes significantly longer: [Shopping Cart Key](https://github.com/user-attachments/files/17195835/Desktop.zip)

I propose that a static image of the render is automatically generated and saved as a thumbnail to be shown on these types of pages. When the page of the object itself is opened, the live render can then execute.

This would save CPU resources and time when flipping through multiple pages, for example when trying to find something quickly.

This could be presented as a togglable option in the settings, for anyone who wants to retain the live render everywhere.

---
An alternative to this would be to handle rendering the 3mf files so that there is less rendering for items such as the example I included above. Perhaps that can be bypassed entirely. You'll notice that if you import the 3mf file, ManyFold takes multiple seconds to render, but if you import the stl file (which I generated using Bambu Studio to load the 3mf, then export only the stl), the filesize of the stl is larger but renders instantly in ManyFold.

I still think having pre-generated thumbnails is the right solution, as that solves any other non-discovered render slowness, and makes navigation overall faster.

**Comment by Floppy** [comment]
Definitely something I want to do. It's already on the list in #1706, so I'll close this as a duplicate if that's OK, but rest assured, it's definitely something we want to do.
