### ISSUE TITLE
Collections tab gives The page you were looking for doesn't exist.

### ISSUE THREAD

**Issue by ZoesDev** [manyfold3d/manyfold#2847]
**Describe the bug**
When you open up the collections tab and do not have any collections available "it will error out with The page you were looking for doesn't exist." This only happens when inside of a library. If you are not in a library and have all models open it is fine. 

**To Reproduce**
1. Open Manyfold
2. Click on a library you have
3. click on collections tab

**Expected behavior**
I would expect the collections tab to work the same in and out of a library and display 

**Screenshots**

<img width="1260" alt="in library" src="https://github.com/user-attachments/assets/6673b734-4d05-48a9-a0d5-6371079d56d8">
<img width="1255" alt="not in a library" src="https://github.com/user-attachments/assets/d169ebcb-0ae2-4496-b20c-635e50aa8eeb">

**Desktop (please complete the following information):**
 - OS: all systems as it is server side issue
 - Browser: 

**Additional context**
This happens on a fresh docker deployment too.  I am using the docker compose with all components in their own containers from the website and running as of the report 0.80.1 (754df235).

**Comment by Floppy** [comment]
Good spot, thank you!
