### ISSUE TITLE
Collections failing to load inconsistently

### ISSUE THREAD

**Issue by gavinmcfall** [manyfold3d/manyfold#2860]
**Describe the bug**
Sometimes when clicking collections at the top of the page. I get an error and this is shown in the logs
```
app 21:39:16 rails.1              | [9a35f276deed6a111bfaaf2adc3c7e27] {"method":"GET","path":"/collections","format":"html","controller":"CollectionsController","action":"index","status":404,"allocations":3120,"duration":20.96,"view":0.0,"db":12.18,"@timestamp":"2024-10-04T08:39:16.763Z","@version":"1","message":"[404] GET /collections (CollectionsController#index)"}
app 21:39:16 rails.1              | [9a35f276deed6a111bfaaf2adc3c7e27]   
app 21:39:16 rails.1              | [9a35f276deed6a111bfaaf2adc3c7e27] ActiveRecord::RecordNotFound (Couldn't find Collection with [WHERE "collections"."public_id" IS NULL]):
app 21:39:16 rails.1              | [9a35f276deed6a111bfaaf2adc3c7e27]   
app 21:39:16 rails.1              | [9a35f276deed6a111bfaaf2adc3c7e27] app/models/concerns/public_i_dable.rb:9:in `find_param'
app 21:39:16 rails.1              | [9a35f276deed6a111bfaaf2adc3c7e27] app/controllers/collections_controller.rb:11:in `index'
app 21:39:16 rails.1              | [9a35f276deed6a111bfaaf2adc3c7e27] app/controllers/application_controller.rb:80:in `switch_locale'
```

**To Reproduce**
1. Click on Collections link at the top of the page

**Expected behavior**
Your collections should load

**Screenshots**
Will upload the next time it happens

**Additional context**
Running in K8S

**Comment by Floppy** [comment]
I suspect this is happening when you have other filters selected. If I'm right, it's the same as issue #2847, which will be fixed in the next release, hopefully coming soon!

(if it's a different thing, please feel free to reopen the ticket)

**Comment by gavinmcfall** [comment]
I have no filters selected, I will just be browsing models in a library, then go to the top of the page and click collections and get this

![image](https://github.com/user-attachments/assets/ce964981-3f53-47a3-92f5-5f8c6a0f7bda)

**Comment by gavinmcfall** [comment]
Maybe the same after reading their description. will wait and see :)

**Comment by Floppy** [comment]
Yep, that's right, the library is a filter :)
