### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#2905]
> Hi @Floppy!! 
> After reviewing the changes applied and the new version of Manyfold I can confirm that all translations are correct except for some components that follow in English because they are not available to translate currently such as the search button

![image](https://github.com/user-attachments/assets/1c3b0119-8772-4ceb-af7a-db66c55f9010)

> And on the other hand, I found a strange error in the html. It seems that when the application is in English everything works correctly but when I make the language change, I have a strange HTML component:

![image](https://github.com/user-attachments/assets/31c077d1-94b6-4807-9439-677b0e2c450b)

![image](https://github.com/user-attachments/assets/2a14ea11-e5a3-4250-9d3d-8b23895f586a)

> I don’t know if you need more information about this, but I am at your disposal to help you

_Originally posted by @juanjomurga in https://github.com/manyfold3d/manyfold/issues/2769#issuecomment-2402907549_

**Comment by Floppy** [comment]
thanks @juanjomurga, good spot on the search button! I think I know what the other thing is too, I'll get it fixed.

**Comment by Floppy** [comment]
#2908 solves both of these issues. Should be in the next release.

**Comment by juanjomurga** [comment]
I have been checking which components don't have a translation. I pass you a list, although I sure that I didn't find all:

**Message when the session on the server expires:**
	Text: _Your session has expired. Please log in again to continue._
 
**Page Upload file:**
	Label _Creator_
	Label _Collection_
	Label _Licence_
	
**Massive Edition**
	Label _Creator_
	Label _Collection_
	Label _Licence_
	Label _New library_
	Label _Organize_
	
	In table list:
		Column _Collection_
		Column _Creator_
		
**Page a model**
	Button Follow
	
**Page Editor of a model**
	Label _Preview file_
	
**Page Massive editor of model files**
	Label _Printed_
	Label _Presupported_
	Label _Y up_
	Button _Split selected files into a new model_
	
	In table:
		Column _Name_

**Page Editor of a model file**
	Label _Presupported version_
	
**Page New Creator**
	TextBox label _Any related web page_

--Page when selecting a creator
	Button _Follow_
	
--Page New Collection
	TextBox label _Any related web page_

**Comment by Floppy** [comment]
Oh, excellent, thank you!

**Comment by Floppy** [comment]
@juanjomurga OK, I've found a couple more untranslatable strings from that list and will sync those up to translation.io. But, the rest should be translatable - have a look at the `activerecord.attributes.*` keys.
