### ISSUE TITLE
Manyfold Docker keeps crashing

### ISSUE THREAD

**Issue by cbram** [manyfold3d/manyfold#2934]
I am running Manyfold as a Docker container together with psotgresql and redis in Unraid. It used to work fine. A couple of weeks ago after an update the container restarted again and again. And this behavior did not change with latest updates.

Here is the error message in the logs. I think it has something to do with ruby but I am not able to nail it down to fix it.
`Preparing database...
/usr/src/app/vendor/bundle/ruby/3.3.0/gems/opengl-bindings-1.6.14/lib/opengl.rb:1: warning: /usr/local/lib/ruby/3.3.0/fiddle.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add fiddle to your Gemfile or gemspec to silence this warning.
Also please contact the author of opengl-bindings-1.6.14 to request adding fiddle into its gemspec.
Illegal option -p
sh: lspci: not found
Illegal option -p
sh: lspci: not found
/usr/src/app/config/initializers/openssl.rb:5: warning: already initialized constant OpenSSL::SSL::SSLContext::DEFAULT_PARAMS
/usr/local/lib/ruby/3.3.0/openssl/ssl.rb:24: warning: previous definition of DEFAULT_PARAMS was here
/usr/src/app/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34: warning: /usr/local/lib/ruby/3.3.0/ostruct.rb was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Also please contact the author of devise_zxcvbn-6.0.0 to request adding ostruct into its gemspec.
2024-10-13T14:54:47.586Z pid=433 tid=gp9 INFO: Sidekiq 7.3.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://manyfold-redis:6380/1"}
== 20240909100000 BackfillActivitiesAfterPermissions: migrating ===============
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

undefined method `uuid=' for an instance of Federails::Actor`

**Desktop (please complete the following information):**
 - OS: Unraid 6.12.11 

I use the latest image from the repo: ghcr.io/manyfold3d/manyfold:latest

**Comment by Floppy** [comment]
I *think* I fixed that in the latest release which just came out. Have you tried v0.82.0 yet?

**Comment by Floppy** [comment]
Actually, no, this is a bit different, I'll fix it now.

**Comment by cbram** [comment]
Just tried the latest version and it did fix it. Thanks a lot.
