### ISSUE TITLE
Support OIDC login

### ISSUE THREAD

**Issue by Natureshadow** [manyfold3d/manyfold#2940]
**Is your feature request related to a problem? Please describe.**

The [Teckids](https://teckids.org/) community would like to host Manyfold for its community, which includes minors as young as 7 years. A self-hosted solution, in contrast to Thingiverse or other commercial offers, generally allows access for young people, and Teckids as an organisation has the capacities and compentences to provide services for children. Hence, Manyfold is a perfect match to get children equally involved ind 3D modelling, printing and re-using/sharing.

However, for safety reasons, Teckids also requires tight identity management and consent tracking, which we do through our central IdM and SSO platform. Hence, all platforms we host must support SSO logins.

**Describe the solution you'd like**

Manyfold should provide support for OIDC logins, probably through the Omniauth library.

**Additional context**

Teckids might be able to sponsor the implementation in Manyfold.

**Comment by Floppy** [comment]
I'm having a go at this with autodiscovery and Auth0; I'll let you know when there's something to try!

**Comment by Floppy** [comment]
So, I've got a draft PR in https://github.com/manyfold3d/manyfold/pull/2946 that works locally! Bit more tidying up to do, and edge cases to handle, but then I'll merge it in and if you like, you could try an experiment with the `edge` docker tag, see if it works for you?

**Comment by Natureshadow** [comment]
Great! Let me know once the image is tagged.

**Comment by Natureshadow** [comment]
I have added a preliminary review of the PR.

**Comment by Floppy** [comment]
Thanks for the review, it was really helpful! Don't often get those working on my own :)

The PR is merged now, so the `edge` build has OIDC support ready to test. See the PR for details of the new environment variables you'll need to set to enable it. Let me know how it goes!
