### ISSUE TITLE
Unable to install docker since 0.81.0

### ISSUE THREAD

**Issue by kqmaverick** [manyfold3d/manyfold#2974]
**Describe the bug**
With docker versions 0.82.0+ migration step is not completing.
[manyfold error.txt](https://github.com/user-attachments/files/17413644/manyfold.error.txt)

**Comment by ToasterUwU** [comment]
I have the same error on a completely fresh install, literally just installed the OS a few hours ago and downloaded and started the container for the very first time

**Comment by Floppy** [comment]
I'm looking into it now; I've seen it do this occasionally where it's failed on a transaction earlier on, and now postgres gets stuck in an invalid state, but if it's happening fresh for two people, there's definitely something up. I'll get back to you soon.

**Comment by Floppy** [comment]
OK, I think I've got a fix - can either of you (@ToasterUwU or @kqmaverick ) try out the `edge` docker tag, see if that fixes it? If so, I'll push out a release asap.

**Comment by ToasterUwU** [comment]
@Floppy I'm gonna test it in max an hour

**Comment by ToasterUwU** [comment]
@Floppy Edge fixed it for me, so whatever you did is the fix

**Comment by Floppy** [comment]
Fantastic :)

**Comment by Floppy** [comment]
ok, v0.84.0 is out with that fix in it. @kqmaverick I hope that fixes it for you, and thanks for the report!
