### ISSUE TITLE
Problems running locally

### ISSUE THREAD

**Issue by ismanapa** [manyfold3d/manyfold#3097]
**Describe the bug**
After executing the command `bin/dev` to run the application locally, I obtain an error in the installing dependencies step. Although the error seems related to a corrupted cache, I have tried to delete the cache but the error still exists.

**To Reproduce**
1. Clone repository
2. Execute `bin/dev`

**Expected behavior**
Application starts

**Screenshots**
![image](https://github.com/user-attachments/assets/9ad2d283-1e77-4df3-8d72-98716d467d5a)

**Desktop (please complete the following information):**
 - OS: WSL

**Comment by Floppy** [comment]
That's an odd one... are you running the `main` branch, or a tag? If you switch to the latest release tag instead, does it do anything differently? I might have broken something in the dependencies by accident in the dev version.

**Comment by ismanapa** [comment]
Hi again! 

I have tried with the latest release tag and the error still appears. But, after that, I have tried with other computer (ubuntu this time) and I have completed this step successfully. So I suppose that the error is related to my windows with WSL.

Now I have a new error related to OpenSSL. I don't know if this is a problem with something missing in my installation or what.

Maybe you know something about that, if not I think that we can close the issue.

Thanks for your help.

![image](https://github.com/user-attachments/assets/2562a8ff-c7e9-4226-8b66-62d2a542a751)

**Comment by Floppy** [comment]
I think that's because that flag is only introduced in more recent versions of OpenSSL; can you check if there's any upgrade available for your system package? I will check the required version...

**Comment by Floppy** [comment]
OK, so OpenSSL went to v3 in Ubunty Jammy, 22.04, but 4 previous Ubuntu releases are still supported or in security maintenance (20.04 LTS, 18.04 LTS, 16.04 LTS, 14.04 LTS), and they only have OpenSSL 1. So, I should fix the code.

**Comment by Floppy** [comment]
OK, there's a fix on `main`, give it a go.

**Comment by ismanapa** [comment]
Thanks! Now all is working and I have started the local environment successfully. Thanks for your support 😁
