### ISSUE TITLE
Feature Request: TrueNAS support

### ISSUE THREAD

**Issue by Luix333** [manyfold3d/manyfold#3129]
Hi, first of all thanks for all the hard work! 

I'd like to know if there are plans to add Manyfold as an app for TrueNAS Scale. Or if there's anyone out there who got it working as a custom container.

**Comment by Floppy** [comment]
Duplicate of #1697 - I've had TrueNAS on the list for a while, but parked it because templating was either non-existent or just difficult. The new release looks like it makes this easier, so I'll take another look at this soon!

**Comment by Luix333** [comment]
@Floppy that would be amazing! 
I just want to add that on [#1697 ](https://github.com/manyfold3d/manyfold/issues/1697) you specifically mention TrueNAS Core, but it's TrueNAS Scale the one that got the new release with support to custom docker apps.
Keep up the good work! I'm excited to give Manyfold a try once it comes to TrueNAS!

**Comment by Gravitom** [comment]
Also chiming in hoping there is TrueNAS Scale support in the future.
