### ISSUE TITLE
"Activity" Button does not use "RAILS_RELATIVE_URL_ROOT"

### ISSUE THREAD

**Issue by capitain-schos** [manyfold3d/manyfold#3158]
**Describe the bug**
In my docker compose I set the env var `RAILS_RELATIVE_URL_ROOT` to `/manyfold`. As far as I can tell everything is working, but clicking the "Activity" button (heartbeat symbol next to Scan and Settings) will bring me to /activity instead of /manyfold/activity.

**To Reproduce**
use default docker compose file from repo.
add env var `RAILS_RELATIVE_URL_ROOT: /manyfold` to the app service.
start up manyfold, create generic user, add generic library, click activity button

**Expected behavior**
target url should be /manyfold/activity

**Screenshots**
I dont think they are helpful

**Desktop (please complete the following information):**
 - OS: Windows 10 and Pop_Os
 - Browser: Firefox
 - Version 132

**Smartphone (please complete the following information):**
 - Device: Motorola edge 30
 - OS: lineageos
 - Browser: fennec F-Droid
 - Version 132

**Additional context**
I run manyfold behind nginx as a reverse proxy and serve a subpath https://example.com/manyfold

**Comment by Floppy** [comment]
Good spot, thank you!

**Comment by capitain-schos** [comment]
As a side note, when i visit https://example.com/manyfold/activity, the site works as expected. Also I did not test anything else (fighting with permissions after upload and some other issue in the database ...)
But you might want to Ctrl+F through your sources, maybe the `RAILS_RELATIVE_URL_ROOT` is missing somewhere else as well?

**Comment by Floppy** [comment]
I did find a few others - all fixed in #3161 and will be in the next release. Thanks again :)

**Comment by capitain-schos** [comment]
No, Thank you :-)
