### ISSUE TITLE
Convert to 3MF process hung up

### ISSUE THREAD

**Issue by TK-3375** [manyfold3d/manyfold#3169]
Steps to replicate :

1. Start the convertion to 3MF
2. Wait...
3. It's generating a new file, but it's basically empty and doesn't work. Also the process doesn't stop (rotating circle keeps going on the button).

Expected behavior :

File should be generated as 3MF

Queue
![image](https://github.com/user-attachments/assets/9e095b00-6927-4642-be9e-f49f904d9bc9)

Failed queue :
![image](https://github.com/user-attachments/assets/65dc5d3e-aa74-48ef-8f48-b9144ece500b)

Including the problematic file (and the generated output)

[Anduins Sword.zip](https://github.com/user-attachments/files/17777840/Anduins.Sword.zip)

**Comment by DarkCeltic** [comment]
I have encountered this same issue. I looked through and found what I believe to be the issue. When converting to 3mf, if the file is not manifold then the conversion will continuously fail. There is an error message in the logs that helped track this down. I confirmed this by downloading the stl, importing and fixing the nonmanifold edges using 3d software and reuploading. After this I am able to convert to 3mf.

**Comment by TK-3375** [comment]
> I have encountered this same issue. I looked through and found what I believe to be the issue. When converting to 3mf, if the file is not manifold then the conversion will continuously fail. There is an error message in the logs that helped track this down. I confirmed this by downloading the stl, importing and fixing the nonmanifold edges using 3d software and reuploading. After this I am able to convert to 3mf.

Can you test out the file I included ? Doesn't respond as wrong in bambu slicer, nor in meshmixer

**Comment by Floppy** [comment]
Ah, that's interesting, there's a lot in the "performance" queue, which is what will be doing the conversion. So it could be queued up in there. On the main sidekiq page, can you see if the performance worker is running? It could just have a lot to work through...

**Comment by TK-3375** [comment]
> Ah, that's interesting, there's a lot in the "performance" queue, which is what will be doing the conversion. So it could be queued up in there. On the main sidekiq page, can you see if the performance worker is running? It could just have a lot to work through...

![image](https://github.com/user-attachments/assets/c834a955-c116-4055-b5f5-abd69e9565c2)
is this what you need ?

**Comment by TK-3375** [comment]
I have restarted the whole server / container this morning, but it still showing with the circle "in progress" thing. Which makes me think the status of the task is stored in the database or something ?

**Comment by Floppy** [comment]
Yes, it is. As I just commented in the other ticket, it's a bit of a hack. I'll revisit it.

**Comment by Floppy** [comment]
> I have encountered this same issue. I looked through and found what I believe to be the issue. When converting to 3mf, if the file is not manifold then the conversion will continuously fail. There is an error message in the logs that helped track this down. I confirmed this by downloading the stl, importing and fixing the nonmanifold edges using 3d software and reuploading. After this I am able to convert to 3mf.

Ah, interesting, it shouldn't retry if it's non-manifold. I can fix that.
