### ISSUE TITLE
Inconsistent display of "convert to 3MF" button across screens

### ISSUE THREAD

**Issue by TK-3375** [manyfold3d/manyfold#3173]
**Describe the bug**
When you click "convert to 3MF" on the problem page the button will animate to indicate the process is ongoing.

If you view the model page directly that button is also there, but it's not indicating that the conversion is in progress

**To Reproduce**
1. Go to problem page
2. Click on convert to 3MF for an "Inefficient format" file.
3. Click on the item name to reach it's dedicated page
4. "Convert to 3MF" button is shown plain, with no animation that the process is ongoing

**Expected behavior**

If a process has been started, the button animation should be consistent across all screens.

**Screenshots**

![image](https://github.com/user-attachments/assets/20dbccac-5daf-4f5b-a7c1-12655590b2c1)

![image](https://github.com/user-attachments/assets/48275f3a-9f28-43ac-8724-c75dd3fc7413)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 130.0.6723.117 

**Additional context**

App installed on a proxmox server, debian 12, through docker.
AMD EPYC 3151 4-Core Processor 
32 gigs of ram

Not sure if a bug but the button on "view model" and the button in alert page don't have the same URL... I expected them to, but nope. Maybe it's intended though.

**Comment by Floppy** [comment]
Good call. The spinner on the problem page is a bit of a hack tbh, I should make it more consistent.
