### ISSUE TITLE
Errors caused by MariaDB JSON serialization

### ISSUE THREAD

**Issue by AevumDecessus** [manyfold3d/manyfold#3188]
**Describe the bug**
![image](https://github.com/user-attachments/assets/4e9f2617-c1a6-4df8-9cb0-dd502cdee040)

**Server Environment**
* Linuxserver docker image [v0.88.0 (06b4dee3)](https://github.com/manyfold3d/manyfold/tree/06b4dee336e0ad37b4250ae80731bafa6a24be90)
* External mariadb database

**To Reproduce**
1. Go to any of the following:\
  * `/models`
  * `/collections`
  * `/admin/files`
2. Immediately receive error message

**Expected behavior**
Expected to view standard pages as normal

**Error Logs**
* `/models`
```I, [2024-11-18T11:15:31.735955 #264]  INFO -- : [c8743cf0-37c9-4f8d-8c05-733c8c82a43e] {"method":"GET","path":"/models","format":"html","controller":"ModelsController","action":"index","status":500,"allocations":305246,"duration":467.39,"view":0.0,"db":29.39,"@timestamp":"2024-11-18T16:15:31.735Z","@version":"1","message":"[500] GET /models (ModelsController#index)"}
F, [2024-11-18T11:15:31.738554 #264] FATAL -- : [c8743cf0-37c9-4f8d-8c05-733c8c82a43e]   
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] ActionView::Template::Error (undefined method `dig' for an instance of String):
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]     12:       data-background-colour="<%= renderer_settings["background_colour"] %>"
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]     13:       data-object-colour="<%= renderer_settings["object_colour"] %>"
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]     14:       data-render-style="<%= renderer_settings["render_style"] %>"
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]     15:       data-auto-load="<%= ((file.size || 9_999_999.megabytes) < ((renderer_settings["auto_load_max_size"] || 9_999_999).megabytes)) ? "true" : "false" %>">
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]     16:     </canvas>
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]     17:     <div class="p-0 btn btn-secondary load-progress object-preview-progress position-absolute top-50 start-50 translate-middle" role="presentation">
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]     18:       <div class="progress-bar bg-info progress-bar-animated progress-bar-striped" aria-label="Loading progress" role="progressbar" style="width: 0%; height: 100%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e]   
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/models/model_file.rb:49:in `size'
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/views/application/_object_preview.html.erb:15
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/components/model_component.html.erb:9:in `call'
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/views/models/_list.html.erb:17
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/views/models/_list.html.erb:1
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/views/models/index.html.erb:1
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/controllers/models_controller.rb:17:in `index'
[c8743cf0-37c9-4f8d-8c05-733c8c82a43e] app/controllers/application_controller.rb:86:in `switch_locale'
```
* `/collections`
```I, [2024-11-18T11:18:03.855342 #264]  INFO -- : [4aa92496-08af-4d98-9bde-36a8431cdc05] {"method":"GET","path":"/collections","format":"html","controller":"CollectionsController","action":"index","status":500,"allocations":358274,"duration":589.6,"view":0.0,"db":37.78,"@timestamp":"2024-11-18T16:18:03.855Z","@version":"1","message":"[500] GET /collections (CollectionsController#index)"}
F, [2024-11-18T11:18:03.858077 #264] FATAL -- : [4aa92496-08af-4d98-9bde-36a8431cdc05]   
[4aa92496-08af-4d98-9bde-36a8431cdc05] ActionView::Template::Error (undefined method `dig' for an instance of String):
[4aa92496-08af-4d98-9bde-36a8431cdc05]     12:       data-background-colour="<%= renderer_settings["background_colour"] %>"
[4aa92496-08af-4d98-9bde-36a8431cdc05]     13:       data-object-colour="<%= renderer_settings["object_colour"] %>"
[4aa92496-08af-4d98-9bde-36a8431cdc05]     14:       data-render-style="<%= renderer_settings["render_style"] %>"
[4aa92496-08af-4d98-9bde-36a8431cdc05]     15:       data-auto-load="<%= ((file.size || 9_999_999.megabytes) < ((renderer_settings["auto_load_max_size"] || 9_999_999).megabytes)) ? "true" : "false" %>">
[4aa92496-08af-4d98-9bde-36a8431cdc05]     16:     </canvas>
[4aa92496-08af-4d98-9bde-36a8431cdc05]     17:     <div class="p-0 btn btn-secondary load-progress object-preview-progress position-absolute top-50 start-50 translate-middle" role="presentation">
[4aa92496-08af-4d98-9bde-36a8431cdc05]     18:       <div class="progress-bar bg-info progress-bar-animated progress-bar-striped" aria-label="Loading progress" role="progressbar" style="width: 0%; height: 100%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
[4aa92496-08af-4d98-9bde-36a8431cdc05]   
[4aa92496-08af-4d98-9bde-36a8431cdc05] app/models/model_file.rb:49:in `size'
[4aa92496-08af-4d98-9bde-36a8431cdc05] app/views/application/_object_preview.html.erb:15
[4aa92496-08af-4d98-9bde-36a8431cdc05] app/views/collections/_collection.html.erb:11
[4aa92496-08af-4d98-9bde-36a8431cdc05] app/views/collections/index.html.erb:15
[4aa92496-08af-4d98-9bde-36a8431cdc05] app/views/collections/index.html.erb:1
[4aa92496-08af-4d98-9bde-36a8431cdc05] app/controllers/collections_controller.rb:32:in `index'
[4aa92496-08af-4d98-9bde-36a8431cdc05] app/controllers/application_controller.rb:86:in `switch_locale'
```
* `/admin/files`
```I, [2024-11-18T11:16:23.391072 #264]  INFO -- : [9e7ef54a-8b28-4303-bd14-3a506aacb0f4] {"method":"GET","path":"/admin/model_files","format":"html","controller":"Admin::ModelFilesController","action":"index","status":500,"allocations":70660,"duration":185.96,"view":0.0,"db":21.45,"@timestamp":"2024-11-18T16:16:23.390Z","@version":"1","message":"[500] GET /admin/model_files (Admin::ModelFilesController#index)"}
F, [2024-11-18T11:16:23.396048 #264] FATAL -- : [9e7ef54a-8b28-4303-bd14-3a506aacb0f4]   
[9e7ef54a-8b28-4303-bd14-3a506aacb0f4] ActionView::Template::Error (undefined method `dig' for an instance of String):
[9e7ef54a-8b28-4303-bd14-3a506aacb0f4]     1: # frozen_string_literal: true
[9e7ef54a-8b28-4303-bd14-3a506aacb0f4]     2: insert_tag renderer_for(:index)
[9e7ef54a-8b28-4303-bd14-3a506aacb0f4]   
[9e7ef54a-8b28-4303-bd14-3a506aacb0f4] app/models/model_file.rb:49:in `size'
[9e7ef54a-8b28-4303-bd14-3a506aacb0f4] app/controllers/application_controller.rb:86:in `switch_locale'
```

**Comment by Floppy** [comment]
Interesting, that's a strange one. It's actually due to the file attachment data in the model, switch_locale is just the outermost method for the request.

Is this for a few specific files, or for everything?

Could you go to the advanced admin area and look at the file list? The path is `/admin/model_files`. If you scroll that list to the right, you should see a column called "attachment_data". Could you tell me what it shows? Mine look like this:

<img width="320" alt="Screenshot 2024-11-18 at 16 29 49" src="https://github.com/user-attachments/assets/fdd52ef7-1e2d-45de-b85b-fdc2d7a7ea70">

If yours look different, that will be a clue. I wonder, as you're using MariaDB, whether this is related to JSON fields on MySQL/MariaDB being a bit... different, somehow.

**Comment by AevumDecessus** [comment]
unfortunately `/admin/model_files` is one of the pages showing this issue

**Comment by Floppy** [comment]
Ah. Good point.

**Comment by AevumDecessus** [comment]
from the rails console
```irb(main):001> puts ModelFile.first.attachment_data.inspect
"{\"id\":\"multibin/multipoint/0-5h/mp9/bin-to-bin-connector/0-5h-bin-to-bin-rail-click-connector#1081/0.5H - Bin-To-Bin Rail Click Connector.stl\",\"storage\":\"library_1\",\"metadata\":{\"filename\":\"0.5H - Bin-To-Bin Rail Click Connector.stl\",\"size\":88184,\"mime_type\":\"application/octet-stream\"}}"
=> nil```


from the DB
`select attachment_data from model_files limit 5;`
```
| "{\"id\":\"ender5plus/enclosure/3dup-ender-5-plus-enclosure#2/3dup-corner-L.stl\",\"storage\":\"library_1\",\"metadata\":{\"filename\":\"3dup-corner-L.stl\",\"size\":716184,\"mime_type\":\"application/octet-stream\"}}"                        |
| "{\"id\":\"assortment-collection/assortment-boxes-40/1x1-square-40#3/assortment box 40 1x1.STL\",\"storage\":\"library_1\",\"metadata\":{\"filename\":\"assortment box 40 1x1.STL\",\"size\":742084,\"mime_type\":\"application/octet-stream\"}}" |
| "{\"id\":\"ender5plus/enclosure/3dup-ender-5-plus-enclosure#2/3dup-corner-R.stl\",\"storage\":\"library_1\",\"metadata\":{\"filename\":\"3dup-corner-R.stl\",\"size\":751484,\"mime_type\":\"application/octet-stream\"}}"                        |
| "{\"id\":\"ender5plus/enclosure/3dup-ender-5-plus-enclosure#2/3dup-ender5plus-tray-lid.stl\",\"storage\":\"library_1\",\"metadata\":{\"filename\":\"3dup-ender5plus-tray-lid.stl\",\"size\":20084,\"mime_type\":\"application/octet-stream\"}}"   |
| "{\"id\":\"ender5plus/enclosure/3dup-ender-5-plus-enclosure#2/3dup-ender5plus-tray.stl\",\"storage\":\"library_1\",\"metadata\":{\"filename\":\"3dup-ender5plus-tray.stl\",\"size\":50784,\"mime_type\":\"application/octet-stream\"}}"           |
```

**Comment by AevumDecessus** [comment]
```
CONTAINER           REPOSITORY                    TAG                 IMAGE ID            SIZE
mariadb             lscr.io/linuxserver/mariadb   latest              97a0f37586f2        335MB
```

**Comment by Floppy** [comment]
OK, that's version 10.11.10 of the server, by the look of it. Thanks. I'll take a look at what might be going on and get back to you!

**Comment by AevumDecessus** [comment]
yeah confirmed version (had to go look up the command again)
```
MariaDB [(none)]> select VERSION();
+----------------------+
| VERSION()            |
+----------------------+
| 10.11.10-MariaDB-log |
+----------------------+
1 row in set (0.000 sec)
```

**Comment by Floppy** [comment]
One more thing - has Manyfold worked at all for you, or has this error hit you straight away?

**Comment by AevumDecessus** [comment]
Manyfold has been working for ages, this only happened when I upgrade to 0.88 from iirc 0.83

**Comment by Floppy** [comment]
OK, thanks - that's odd. I've got another report of the same issue, so there's definitely something gone wrong somewhere.

**Comment by Floppy** [comment]
@AevumDecessus any chance you could try to run some different versions instead of `latest` and see when the error appears? Since 0.83 (which was only a month ago) there haven't been any major changes to the database that will cause incompatibilities, so you should be safe enough to try the ones in between.

**Comment by AevumDecessus** [comment]
* 0.83.0 - works
* 0.84.1 - works
* 0.85.1 - works
* 0.86.0 - works
* 0.87.0 - broken
* 0.88.0 - broken

Looks like the problem was include in the 0.87.0 release

**Comment by Floppy** [comment]
fantastic, thanks, that'll really narrow it down!

**Comment by Floppy** [comment]
Good news, I've got it replicated locally...

**Comment by Floppy** [comment]
OK, it broke in 78c59b83d7a3bd61b11388fc89903f281340d88c

**Comment by Floppy** [comment]
Right, I think this should be fixed! If you want, give the `edge` image a try, or wait for the next release, probably tomorrow.

**Comment by AevumDecessus** [comment]
Can confirm, everything is good in the 0.89.0 release, thanks for the quick deep dive and resolution!
