### ISSUE TITLE
Scan reports error IOError: closed stream

### ISSUE THREAD

**Issue by lambi21** [manyfold3d/manyfold#3314]
**Describe the bug**
When scanning new files, scanning seems to run fine, but checking Sidekiq reports a bunch of IO errors (IOError: closed stream). Also, these do not get resolved on retries.

**Screenshots**
![image](https://github.com/user-attachments/assets/7cc99f35-ff7c-4c10-b026-e1becc8880c2)
![image](https://github.com/user-attachments/assets/449b634f-300d-4fc2-921f-e953ce682b55)

**Desktop (please complete the following information):**
 - run on Unraid
 - running manyfold-solo:latest (0.91.2)

**Additional context**
does not seem to be an issue with folder owner or permissions, current settings on folder in question:
![image](https://github.com/user-attachments/assets/bc27e794-f21c-464b-96dc-397510e51a2e)

**Comment by Floppy** [comment]
OK, this should be fixed in v0.91.3, now released. Thanks again for the report!
