### ISSUE TITLE
Feature Request - Unraid support

### ISSUE THREAD

**Issue by jtcm222** [manyfold3d/manyfold#451]
Would it be possible to create an Unraid docker template for this to simplify the installation? I'm not sure what would be required (sorry).

**Comment by Floppy** [comment]
Sounds good! Don't know what's involved either, but I can try to find out :)

**Comment by Floppy** [comment]
Would adding it to [CA](https://forums.unraid.net/topic/38582-plug-in-community-applications/) be the best way to make this easy for Unraid users?

**Comment by jtcm222** [comment]
> Would adding it to [CA](https://forums.unraid.net/topic/38582-plug-in-community-applications/) be the best way to make this easy for Unraid users?

That would be great. That's how docker containers are typically added to unraid. If you put it on there I'll give it a test.

**Comment by Floppy** [comment]
I didn't get to it yet I'm afraid!

**Comment by jonathanfrem** [comment]
I am running Van_Dam on Unraid using Portainer, however CA or Dockerhub would make it easier.

**Comment by jtcm222** [comment]
> I am running Van_Dam on Unraid using Portainer, however CA or Dockerhub would make it easier.

Would it be possible for you to share your setup/settings? I'd love to get this running on my server.

**Comment by jonathanfrem** [comment]
> Would it be possible for you to share your setup/settings? I'd love to get this running on my server.

Sure! I am running the Postgresql 13 that is on CA, and running Portainer with the docker compose. If you have a look at the linked video on the readme, that guy is using Portainer, so I tried just working backwards from that. 

If you want you can DM me on discord if you need more specific help :) Get Java#6497

**Comment by MountainGod2** [comment]
I don't currently have a 3D printer, but I had some free time and did up a template for a buddy yesterday and added it to CA if that's alright with you. 
https://github.com/MountainGod2/unraid-templates/blob/main/van_dam/van_dam.xml

It's essentially just a copy/paste translation of the example docker-compose and depends on the user already having redis and postgres containers running.

I've tried to make the instructions as verbose as possible, but as there's no way to support compose or multi-container installs in Unraid out of the box, there's not much that can be done to make it too too much easier within unraid's template system as is.

I'm open to ideas/suggestions though, or if you'd rather use my xml as a jumping-off point to make your own, feel free. Looks like a handy tool!

![image](https://user-images.githubusercontent.com/88257202/229244696-15232588-04dd-4f67-bc99-4da007b9a7d6.png)

![image](https://user-images.githubusercontent.com/88257202/229243063-8b740a54-0805-47c5-8d92-53c710e86a2e.png)

![image](https://user-images.githubusercontent.com/88257202/229245749-b8a7d8e9-c7e9-45f1-9fd3-8ea30d22dfad.png)

![image](https://user-images.githubusercontent.com/88257202/229243743-91733916-a864-49f4-9631-9991e7e0e766.png)

**Comment by jtcm222** [comment]
> I don't currently have a 3D printer, but I had some free time and did up a template for a buddy yesterday and added it to CA if that's alright with you. https://github.com/MountainGod2/unraid-templates/blob/main/van_dam/van_dam.xml
> 
> It's essentially just a copy/paste translation of the example docker-compose and depends on the user already having redis and postgres containers running.
> 
> I've tried to make the instructions as verbose as possible, but as there's no way to support compose or multi-container installs in Unraid out of the box, there's not much that can be done to make it too too much easier within unraid's template system as is.
> 
> I'm open to ideas/suggestions though, or if you'd rather use my xml as a jumping-off point to make your own, feel free. Looks like a handy tool!
> 
> ![image](https://user-images.githubusercontent.com/88257202/229244696-15232588-04dd-4f67-bc99-4da007b9a7d6.png)
> 
> ![image](https://user-images.githubusercontent.com/88257202/229243063-8b740a54-0805-47c5-8d92-53c710e86a2e.png)
> 
> ![image](https://user-images.githubusercontent.com/88257202/229245749-b8a7d8e9-c7e9-45f1-9fd3-8ea30d22dfad.png)
> 
> ![image](https://user-images.githubusercontent.com/88257202/229243743-91733916-a864-49f4-9631-9991e7e0e766.png)

Got it working! Thanks for this! I'm adding files now and playing around.

**Comment by Floppy** [comment]
@MountainGod2 Oh, that's fantastic, thank you! I'll add it into the README / installation instructions. Would it make sense to include that XML file for unraid in this repository? I don't really know how it all works in Unraid land... :)

**Comment by MountainGod2** [comment]
@Floppy 
Honestly unless you want to go through the rigamarole of creating a separate repo and having Squid (the admin of Unraid's Community App's) approve and add it to the store, there's not a huge need in my opinion.

Essentially how it works is that when you create a new docker container inside of Unraid's UI, it generates and saves a corresponding .xml which in turn executes the appropriate docker run commands when the user interacts with the container from the web management page.

The CA store is just a collection of those .xml files so that people can install them a bit more conveniently without having to add the various environment variables/data paths themselves. 

Here's a decent resource from the forum if you did want to add an "official" version of the template though 🙂 
https://forums.unraid.net/topic/57181-docker-faq/#comment-566084
(scroll down to the section titled "Publishing to CA")

**Comment by Floppy** [comment]
I suppose I'm mainly wondering about what happens if I add a new environment variable, for instance. Would you need to update your XML for the new release?

**Comment by MountainGod2** [comment]
I see what you mean. Yeah, it would need to be updated, it will keep up to date with `:latest`, but anything outside of that would need to be added in the XML. And seeing as I don't actively use van_dam myself currently, that could definitely be an issue down the road.

That being said, it's pretty easy to add things, so if someone were to open a PR (I have the support link on the store pointing at this repo) and drop me a mention, I'd be happy to fix it.

Or if you want to make your own repo for the template so you can integrate it into your deployment process, no worries! I could help if you have any questions.

**Comment by Floppy** [comment]
Thanks! I'll have a think about the right approach and see where I end up. Thanks again for making the template!

**Comment by Floppy** [comment]
@MountainGod2 I've got an organisation set up for this project now, so I will probably look at adopting the unraid config you've done into a separate repo at some point soon. 👍🏻

**Comment by Floppy** [comment]
@MountainGod2 I've adopted and updated the template at https://github.com/manyfold3d/unraid-templates, with credit to your original work. I need to look at getting this into the official store now!

**Comment by Floppy** [comment]
I've got in touch, hopefully we'll have the official repo in there soon 🎉

**Comment by totalanni** [comment]
Is it possible to get a version with the depends(postgres/redist) built into the container?

**Comment by Floppy** [comment]
@totalanni that's something I do want to do, probably as part of #977 and #27.

**Comment by twistedsanity** [comment]
> Is it possible to get a version with the depends(postgres/redist) built into the container?

As much having an AIO template is convenient, it goes against the point of a container. You should really only look to ever run a single service/process per container. If you want an easier deployment with the extra dependencies, look to docker compose where you can have a stack defined to install all of the extra requirements linked/configured to the main container. Unraid can utilise docker compose in the UI with a plugin (compose manager) and a few manual steps.

**Comment by totalanni** [comment]
> @totalanni that's something I do want to do, probably as part of #977 and #27.

Ty! Looking forward to a solution to keep all my models organized.

> > Is it possible to get a version with the depends(postgres/redist) built into the container?
> 
> As much having an AIO template is convenient, it goes against the point of a container. You should really only look to ever run a single service/process per container. If you want an easier deployment with the extra dependencies, look to docker compose where you can have a stack defined to install all of the extra requirements linked/configured to the main container. Unraid can utilise docker compose in the UI with a plugin (compose manager) and a few manual steps.

Most Unraid users use it for its simplicity. While I'm sure if I bang my head for a few days on it, I would be able to get it going, the beauty of an AIO container sounds much better.

I have tried to create my own Postgres15 and redis container but can not get it to connect to the postgres server. I imagine it is me not being able to figure out how to properly add the user "manyfold" and the DB correctly in adminer.

Anyone on discord that could give me some pointers? xD

**Comment by twistedsanity** [comment]
In unraid to connect to another container either use 127.0.0.1 or the name of the container if on a custom network, as it uses its own internal networking, not your actual unraid IP.

**Comment by totalanni** [comment]
I found my problem. 
It appears that the default Unraid template defaults to "Docker Network = None"

**Comment by Floppy** [comment]
Ooh; that might be something I can fix in the template then...

**Comment by tjorim** [comment]
Should we switch to a version that uses sqlite so it's a single container for convenience?

**Comment by Floppy** [comment]
I was thinking to change this over to use the solo instance, yes, once I know it's stable :)

**Comment by kwiksilver** [comment]
I started using the linuxserver.io version of Manyfold on Unraid in conjunction with the redis and mariadb docker containers, also on Unraid. Everything has been working well.

**Comment by HappyPants9999** [comment]
I simply could not figure out how to connect the postgress database so I gave up on using the template and just used compose instead.

**Comment by Floppy** [comment]
The template has changed to use the solo image, so no external databases and networking config are required now.
