### ISSUE TITLE
Proper multi-user capability

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#647]
We technically have multiple users under the hood, but the UI around adding, logging in, etc, is totally unwritten. We should finish it off and get proper multiuser support going.

* groundwork: #1920 
* policy enforcement: #1940
* enabling login and signup #1955
* basic role management (readonly, admin): #1963 
* apply roles to existing operations: #1965 
* style new pages: #1967 
* simple upgrade path for existing installs, to set an admin password: #1969 

NLNet Milestone 3.2

**Comment by ksuquix** [comment]
While you are doing this, take into consideration doing permissions per-library as well.

**Comment by beniroquai** [comment]
That would be great. Do Ou consider users being able to upload files to the directory too? I think this would become really useful :)

**Comment by Floppy** [comment]
In time, upload may be a thing, yes.

**Comment by Netrecov** [comment]
i wonder if you could add the user via the postgres sqwl database, and attempt to use the new user to login that way?

**Comment by Jafner** [comment]
This feature is pretty important to me. I want to share my models with my friends, but I'd prefer they not have the ability to delete models from my collection.
