### ISSUE TITLE
bulk edit files in model workflow issue

### ISSUE THREAD

**Issue by ksuquix** [manyfold3d/manyfold#796]
workflow:
 click bulk edit files
 select stls
 choose Y up
 update selected files
..... 
Have to click back twice to get to model.

I'd suggest two separate changes here.  
1) go back to the model automatically on update
2) link at top of page to just go back to the model

There are actually a few places that could use a link to go back to the model (edit/whatnot), but this is the most obvious as the update button doesn't go back

**Comment by Floppy** [comment]
Yes! The missing breadcrumb annoys me all the time. Do you think going back to the model automatically after bulk edit is the right default thing to do? Makes sense, really...

**Comment by ksuquix** [comment]
I just had a thought... there isn't a reason you can't have an "Update and State" and an "Update and Return"
