### ISSUE TITLE
Font Errors

### ISSUE THREAD

**Issue by NickSica** [manyfold3d/manyfold#891]
Hello,

I have van_dam in a container behind an nginx reverse proxy with both the RAILS_RELATIVE_URL_ROOT and the nginx proxy pointing to /vandam. When I load up the webpage I get font errors and they don't load.
![image](https://user-images.githubusercontent.com/26910401/208597557-b5c2eaf1-aaab-4115-945d-92dba6e577a1.png)
![image](https://user-images.githubusercontent.com/26910401/208597416-d2a615f9-3184-4d45-892d-90334e81c4f0.png)

Connecting directly to the ip and port without the reverse proxy I get the following error which leads me to believe that the url root is not being applied correctly in some instances.
![image](https://user-images.githubusercontent.com/26910401/208597510-6818a760-f38d-4c51-a544-946deccb9a9d.png)

The advanced admin interface(and sometimes the library creation button) seems to be plagued by the same bug(sometimes I can get to the advanced admin interface but not often).

**Comment by Floppy** [comment]
Interesting, thanks for the detailed report! I wonder if this is also the cause behind #448 as well.

Definitely looks like RAILS_RELATIVE_URL_ROOT isn't being used for those asset files; I'll fix that, and then we can see if it's happier behind the proxy.

**Comment by Floppy** [comment]
This is because the asset URL inside the bootstrap-icons CSS is wrong. We should be able to fix it by doing something like  `$bootstrap-icons-font-dir: asset-path("bootstrap-icons/font/fonts")` at the top of `application.bootstrap.scss` but when I tried it, the asset-path helper wasn't being called, it went in as a literal. Still, got most of the solution.

**Comment by NickSica** [comment]
![image](https://github.com/manyfold3d/manyfold/assets/26910401/6af9cc7f-4833-45a3-bd8c-39adba26e3e6)
Changing the value in the url and prepending "/manyfold" (my subdirectory) fixes the issues, but I'm having issues when trying to carry these changes over to the scss file you mentioned. I'm not too familiar with how some things in this build system work which I think is causeing issues for me. I've tried the following code in that file, but the application doesn't seem to grab the changes I make?

Overriding the font-face attribute with: 
```
@font-face {
    font-family: "bootstrap-icons";
    src: url(/manyfold/assets/bootstrap-icons/font/fonts/bootstrap-icons-4f186bfcba02df32e2e45e64645aa46886457cb855a85bbec8013e1866c8a1f6.woff2?24e3eb84d0bcaf83d77f904c78ac1f47) format("woff2"),url(/manyfold/assets/bootstrap-icons/font/fonts/bootstrap-icons-69de61f24e1c47410e9c685931afab4ca0ebba40d9ebbf50c669f7496b112f32.woff?24e3eb84d0bcaf83d77f904c78ac1f47) format("woff");
}
```

Setting bootstrap-icons-font-src(i'm not sure if this is an actual variable or not that's of use):
```
$bootstrap-icons-font-src: url(/manyfold/assets/bootstrap-icons/font/fonts/bootstrap-icons-4f186bfcba02df32e2e45e64645aa46886457cb855a85bbec8013e1866c8a1f6.woff2?24e3eb84d0bcaf83d77f904c78ac1f47) format("woff2"),url(/manyfold/assets/bootstrap-icons/font/fonts/bootstrap-icons-69de61f24e1c47410e9c685931afab4ca0ebba40d9ebbf50c669f7496b112f32.woff?24e3eb84d0bcaf83d77f904c78ac1f47) format("woff");
```

I've basically hit a wall and don't need a flexible fix just a quick band-aid to get this to a working state(as my attempts show). Thank you.

**Comment by Floppy** [comment]
Thanks for pinging back, I'd completely forgotten about this. I'll see if I can take a look soon.

**Comment by Floppy** [comment]
Nope, I thought I had this, but I don't yet. It works fine in dev now, which is a start, but the problem now is that the precompile happens *once* during docker build, and the relative root isn't set at that point (because that precompile is the same for everyone). I wonder if I can get the container to edit the asset paths on the fly at boot...

**Comment by NickSica** [comment]
> Nope, I thought I had this, but I don't yet. It works fine in dev now, which is a start, but the problem now is that the precompile happens _once_ during docker build, and the relative root isn't set at that point (because that precompile is the same for everyone). I wonder if I can get the container to edit the asset paths on the fly at boot...

Probably why I wasn't seeing my changes either. Thank you!
